<a href="https://colab.research.google.com/github/tivanello/fase5/blob/main/notebooks/fase5_pergunta10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
# ============================================================
# BLOCO 1 —IMPORTAR O DATAFRAME do Git
# Objetivo:
# - Clonar o repositório no Colab
# - Localizar o arquivo tratado
# - Carregar o arquivo df_fase5.csv em um DataFrame
# ============================================================

import os
import pandas as pd

REPO_DIR = "/content/fase5"
ARQUIVO = f"{REPO_DIR}/data/processed/df_fase5.csv"

# Clonar o repositório apenas se ainda não existir
if not os.path.exists(REPO_DIR):
    !git clone https://github.com/tivanello/fase5.git {REPO_DIR}
else:
    print("Repositório já existe no ambiente.")

# Carregar o arquivo
df_fase5_p10 = pd.read_csv(ARQUIVO)

# Conferência inicial
print("Dimensão do dataframe:", df_fase5_p10.shape)
display(df_fase5_p10.head())

Repositório já existe no ambiente.
Dimensão do dataframe: (3030, 72)

,RA,Fase,Turma,Ano nasc,Idade 22,Gênero,Ano ingresso,Instituição de ensino,Pedra 20,Pedra 21,...,Avaliador6_id,FaseIdeal_txt,Fase_num,Fase_sufixo,FaseIdeal_num,ra_num,INDE_final,INDE_fonte,PEDRA_final,PEDRA_fonte
0,RA-1,7,A,2003.0,19.0,Menina,2016,Escola Pública,Ametista,Ametista,...,NaN,Fase 8 (Universitários),7.0,NaN,8,1,5.783,INDE 2022,Quartzo,Pedra 2022
1,RA-2,7,A,2005.0,17.0,Menina,2017,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,2,7.055,INDE 2022,Ametista,Pedra 2022
2,RA-3,7,A,2005.0,17.0,Menina,2016,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,3,6.591,INDE 2022,Ágata,Pedra 2022
3,RA-4,7,A,2005.0,17.0,Menino,2017,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,4,5.951,INDE 2022,Quartzo,Pedra 2022
4,RA-5,7,A,2005.0,17.0,Menina,2016,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,5,7.427,INDE 2022,Ametista,Pedra 2022

In [40]:
df_fase5_p10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 72 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     3030 non-null   object
 1   Fase                   3030 non-null   object
 2   Turma                  3030 non-null   object
 3   Ano nasc               860 non-null    float64
 4   Idade 22               860 non-null    float64
 5   Gênero                 3030 non-null   object
 6   Ano ingresso           3030 non-null   int64
 7   Instituição de ensino  3029 non-null   object
 8   Pedra 20               754 non-null    object
 9   Pedra 21               1061 non-null   object
 10  Pedra 22               1932 non-null   object
 11  INDE 22                1932 non-null   float64
 12  Cg                     860 non-null    float64
 13  Cf                     860 non-null    float64
 14  Ct                     860 non-null    float64
 15  Nº Av                  2954 non-null   float64
 16  Avaliador1             2827 non-null   object
 17  Rec Av1                860 non-null    object
 18  Avaliador2             2827 non-null   object
 19  Rec Av2                860 non-null    object
 20  Avaliador3             2034 non-null   object
 21  Rec Av3                860 non-null    object
 22  Avaliador4             1051 non-null   object
 23  Rec Av4                296 non-null    object
 24  IAA                    2865 non-null   float64
 25  IEG                    2954 non-null   float64
 26  IPS                    2859 non-null   float64
 27  Rec Psicologia         860 non-null    object
 28  IDA                    2852 non-null   float64
 29  Matem                  858 non-null    float64
 30  Portug                 858 non-null    float64
 31  Inglês                 283 non-null    float64
 32  Indicado               860 non-null    object
 33  Atingiu PV             860 non-null    object
 34  IPV                    2852 non-null   float64
 35  IAN                    3030 non-null   float64
 36  Destaque IEG           860 non-null    object
 37  Destaque IDA           860 non-null    object
 38  Destaque IPV           860 non-null    object
 39  ano_base               3030 non-null   int64
 40  INDE 2023              931 non-null    float64
 41  Pedra 2023             931 non-null    object
 42  Data de Nasc           2170 non-null   object
 43  Idade                  2170 non-null   float64
 44  Pedra 23               690 non-null    object
 45  INDE 23                690 non-null    float64
 46  IPP                    1992 non-null   float64
 47  Mat                    1988 non-null   float64
 48  Por                    1987 non-null   float64
 49  Ing                    808 non-null    float64
 50  INDE 2024              1054 non-null   float64
 51  Pedra 2024             1092 non-null   object
 52  Avaliador5             148 non-null    object
 53  Avaliador6             6 non-null      object
 54  Escola                 1155 non-null   object
 55  Ativo/ Inativo         1156 non-null   object
 56  Defasagem_final        3030 non-null   int64
 57  Avaliador1_id          2827 non-null   float64
 58  Avaliador2_id          2827 non-null   float64
 59  Avaliador3_id          2034 non-null   float64
 60  Avaliador4_id          1051 non-null   float64
 61  Avaliador5_id          148 non-null    float64
 62  Avaliador6_id          6 non-null      float64
 63  FaseIdeal_txt          3030 non-null   object
 64  Fase_num               2603 non-null   float64
 65  Fase_sufixo            922 non-null    object
 66  FaseIdeal_num          3030 non-null   int64
 67  ra_num                 3030 non-null   int64
 68  INDE_final             2845 non-null   float64
 69  INDE_fonte             2845 non-null   object
 70  PEDRA_final            2883 non-null   object
 71  PEDRA_fonte            2883 non-null   object
dtypes: float64(32), int64(5), object(35)
memory usage: 1.7+ MB

In [41]:
# ============================================================
# BLOCO 2 — LISTAR TODAS AS COLUNAS RELACIONADAS A "FASE"
# Objetivo:
# - Encontrar no df_fase5 todas as colunas cujo nome contenha "fase"
# - Ignorar maiúsculas e minúsculas
# ============================================================

colunas_fase = [col for col in df_fase5_p10.columns if "fase" in col.lower()]

print("Colunas relacionadas a 'fase':")
for col in colunas_fase:
    print("-", col)

print("\nTotal encontrado:", len(colunas_fase))

Colunas relacionadas a 'fase':
- Fase
- FaseIdeal_txt
- Fase_num
- Fase_sufixo
- FaseIdeal_num

Total encontrado: 5

In [43]:
# ============================================================
# BLOCO 3.1 — INSPECIONAR CAMPOS DE FASE
# Objetivo:
# - Ver todos os valores distintos das colunas ligadas à fase
# - Ver como elas se combinam entre si
# ============================================================

df_base = df_fase5_p10.copy()

colunas_fase = [
    "Fase",
    "FaseIdeal_txt",
    "Fase_num",
    "Fase_sufixo",
    "FaseIdeal_num"
]

print("============================================================")
print("VALORES DISTINTOS POR COLUNA")
print("============================================================")

for col in colunas_fase:
    print(f"\nColuna: {col}")
    print(f"Quantidade de valores distintos: {df_base[col].nunique(dropna=False)}")
    valores = df_base[col].drop_duplicates().tolist()
    print(valores)

print("\n============================================================")
print("COMBINAÇÕES ÚNICAS ENTRE AS COLUNAS")
print("============================================================")

df_combinacoes_fase = (
    df_base[colunas_fase]
    .drop_duplicates()
    .sort_values(["Fase_num", "Fase", "Fase_sufixo", "FaseIdeal_num", "FaseIdeal_txt"], na_position="last")
    .reset_index(drop=True)
)

display(df_combinacoes_fase)

print("\n============================================================")
print("CONTAGEM POR COMBINAÇÃO")
print("============================================================")

df_contagem_fase = (
    df_base
    .groupby(colunas_fase, dropna=False)
    .size()
    .reset_index(name="qtd")
    .sort_values(["Fase_num", "Fase", "Fase_sufixo", "FaseIdeal_num", "FaseIdeal_txt"], na_position="last")
    .reset_index(drop=True)
)

display(df_contagem_fase)

============================================================
VALORES DISTINTOS POR COLUNA
============================================================

Coluna: Fase
Quantidade de valores distintos: 88
['7', '6', '5', '4', '3', '2', '1', '0', 'ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', 'FASE 8', '1A', '1B', '1C', '1D', '1E', '1G', '1H', '1J', '1K', '1L', '1M', '1N', '1P', '1R', '2A', '2B', '2C', '2D', '2G', '2H', '2I', '2K', '2L', '2M', '2N', '2P', '2R', '2U', '3A', '3B', '3C', '3D', '3F', '3G', '3H', '3I', '3K', '3L', '3M', '3N', '3P', '3R', '3U', '4A', '4B', '4C', '4F', '4H', '4L', '4M', '4N', '4R', '5A', '5B', '5C', '5D', '5F', '5G', '5L', '5M', '5N', '6A', '6L', '7A', '7E', '8A', '8B', '8D', '8E', '8F', '9']

Coluna: FaseIdeal_txt
Quantidade de valores distintos: 11
['Fase 8 (Universitários)', 'Fase 7 (3º EM)', 'Fase 6 (2º EM)', 'Fase 5 (1º EM)', 'Fase 3 (7º e 8º ano)', 'Fase 4 (9º ano)', 'Fase 2 (5º e 6º ano)', 'Fase 1 (4º ano)', 'ALFA (2º e 3º ano)', 'ALFA (1º e 2º ano)', 'Fase 1 (3º e 4º ano)']

Coluna: Fase_num
Quantidade de valores distintos: 11
[7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.0, nan, 8.0, 9.0]

Coluna: Fase_sufixo
Quantidade de valores distintos: 18
[nan, 'a', 'b', 'c', 'd', 'e', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 'i', 'u', 'f']

Coluna: FaseIdeal_num
Quantidade de valores distintos: 8
[8, 7, 6, 5, 3, 4, 2, 1]

============================================================
COMBINAÇÕES ÚNICAS ENTRE AS COLUNAS
============================================================

     Fase            FaseIdeal_txt  Fase_num Fase_sufixo  FaseIdeal_num
0       0          Fase 1 (4º ano)       0.0         NaN              1
1       0       ALFA (2º e 3º ano)       0.0         NaN              2
2       0     Fase 2 (5º e 6º ano)       0.0         NaN              2
3       0     Fase 3 (7º e 8º ano)       0.0         NaN              3
4       1          Fase 1 (4º ano)       1.0         NaN              1
..    ...                      ...       ...         ...            ...
271     9  Fase 8 (Universitários)       9.0         NaN              8
272  ALFA       ALFA (1º e 2º ano)       NaN         NaN              1
273  ALFA     Fase 1 (3º e 4º ano)       NaN         NaN              1
274  ALFA     Fase 2 (5º e 6º ano)       NaN         NaN              2
275  ALFA     Fase 3 (7º e 8º ano)       NaN         NaN              3

[276 rows x 5 columns]

============================================================
CONTAGEM POR COMBINAÇÃO
============================================================

     Fase            FaseIdeal_txt  Fase_num Fase_sufixo  FaseIdeal_num  qtd
0       0          Fase 1 (4º ano)       0.0         NaN              1   68
1       0       ALFA (2º e 3º ano)       0.0         NaN              2   69
2       0     Fase 2 (5º e 6º ano)       0.0         NaN              2   52
3       0     Fase 3 (7º e 8º ano)       0.0         NaN              3    1
4       1          Fase 1 (4º ano)       1.0         NaN              1   28
..    ...                      ...       ...         ...            ...  ...
271     9  Fase 8 (Universitários)       9.0         NaN              8   38
272  ALFA       ALFA (1º e 2º ano)       NaN         NaN              1  163
273  ALFA     Fase 1 (3º e 4º ano)       NaN         NaN              1  192
274  ALFA     Fase 2 (5º e 6º ano)       NaN         NaN              2   71
275  ALFA     Fase 3 (7º e 8º ano)       NaN         NaN              3    1

[276 rows x 6 columns]

In [45]:
# ============================================================
# BLOCO 3.2 — TRATAR ALFA COMO FASE 0
# Objetivo:
# - Padronizar a coluna Fase_num
# - Considerar ALFA como fase 0
# ============================================================

import pandas as pd
import numpy as np

df_fase5_p10 = df_fase5_p10.copy()

df_fase5_p10["Fase_num"] = pd.to_numeric(df_fase5_p10["Fase_num"], errors="coerce")
df_fase5_p10["FaseIdeal_num"] = pd.to_numeric(df_fase5_p10["FaseIdeal_num"], errors="coerce")

mask_alfa = df_fase5_p10["Fase"].astype(str).str.strip().str.upper().eq("ALFA")

total_alfa = mask_alfa.sum()
nulos_antes = df_fase5_p10.loc[mask_alfa, "Fase_num"].isna().sum()

df_fase5_p10.loc[mask_alfa, "Fase_num"] = 0

print("AJUSTE ALFA -> 0")
print("Total de registros com Fase = ALFA:", total_alfa)
print("Registros ALFA com Fase_num nulo antes do ajuste:", nulos_antes)

print("\nValores únicos de Fase_num após o ajuste:")
print(sorted(df_fase5_p10["Fase_num"].dropna().unique()))

AJUSTE ALFA -> 0
Total de registros com Fase = ALFA: 427
Registros ALFA com Fase_num nulo antes do ajuste: 427

Valores únicos de Fase_num após o ajuste:
[np.float64(0.0), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]

In [46]:
# ============================================================
# BLOCO 3.3 — COMPARAR Fase_num COM FaseIdeal_num
# Objetivo:
# - Ver nulos
# - Ver distribuição
# - Ver cruzamento entre fase atual e fase ideal
# ============================================================

print("Nulos por coluna:")
print(df_fase5_p10[["Fase_num", "FaseIdeal_num"]].isna().sum())

print("\nValores únicos de Fase_num:")
print(sorted(df_fase5_p10["Fase_num"].dropna().unique()))

print("\nValores únicos de FaseIdeal_num:")
print(sorted(df_fase5_p10["FaseIdeal_num"].dropna().unique()))

print("\nCruzamento Fase_num x FaseIdeal_num:")
tabela_cruzada = pd.crosstab(
    df_fase5_p10["Fase_num"],
    df_fase5_p10["FaseIdeal_num"],
    dropna=False
)

display(tabela_cruzada)

print("\nAmostra para conferência:")
display(
    df_fase5_p10[
        ["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]
    ].head(20)
)

Nulos por coluna:
Fase_num         0
FaseIdeal_num    0
dtype: int64

Valores únicos de Fase_num:
[np.float64(0.0), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]

Valores únicos de FaseIdeal_num:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

Cruzamento Fase_num x FaseIdeal_num:

FaseIdeal_num    1    2    3    4   5   6   7    8
Fase_num
0.0            423  192    2    0   0   0   0    0
1.0            123  354   69    4   0   0   0    0
2.0              5  231  274   27   2   1   0    0
3.0              0   38  253  130  52  15   2    1
4.0              0    1   41   84  99  47  11    2
5.0              0    0    5   26  53  78  58    5
6.0              0    0    0    0   0  25  44    7
7.0              0    0    0    0  18  11  30   22
8.0              0    0    0    0   0   0   2  125
9.0              0    0    0    0   0   0   0   38

Amostra para conferência:

       RA  ano_base Fase  Fase_num            FaseIdeal_txt  FaseIdeal_num
0    RA-1      2022    7       7.0  Fase 8 (Universitários)              8
1    RA-2      2022    7       7.0           Fase 7 (3º EM)              7
2    RA-3      2022    7       7.0           Fase 7 (3º EM)              7
3    RA-4      2022    7       7.0           Fase 7 (3º EM)              7
4    RA-5      2022    7       7.0           Fase 7 (3º EM)              7
5    RA-6      2022    7       7.0  Fase 8 (Universitários)              8
6    RA-7      2022    7       7.0  Fase 8 (Universitários)              8
7    RA-8      2022    7       7.0  Fase 8 (Universitários)              8
8    RA-9      2022    7       7.0  Fase 8 (Universitários)              8
9   RA-10      2022    7       7.0  Fase 8 (Universitários)              8
10  RA-11      2022    7       7.0  Fase 8 (Universitários)              8
11  RA-12      2022    7       7.0           Fase 7 (3º EM)              7
12  RA-13      2022    7       7.0  Fase 8 (Universitários)              8
13  RA-14      2022    7       7.0  Fase 8 (Universitários)              8
14  RA-15      2022    7       7.0  Fase 8 (Universitários)              8
15  RA-16      2022    7       7.0  Fase 8 (Universitários)              8
16  RA-17      2022    7       7.0  Fase 8 (Universitários)              8
17  RA-18      2022    7       7.0  Fase 8 (Universitários)              8
18  RA-19      2022    7       7.0  Fase 8 (Universitários)              8
19  RA-20      2022    7       7.0  Fase 8 (Universitários)              8

In [47]:
# ============================================================
# BLOCO 3.4  — PADRONIZAR COLUNA Fase COMO a expressão "FASE XXXX"
# Objetivo:
# - Acrescentar a expressão "FASE " antes do número da fase
# - Manter apenas o número da própria coluna Fase
# ============================================================

df_fase5_p10["Fase"] = (
    pd.to_numeric(df_fase5_p10["Fase"], errors="coerce")
    .astype("Int64")
    .astype("string")
    .radd("FASE ")
)

print("Amostra para conferência:")
display(df_fase5_p10[["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]].head(20))

Amostra para conferência:

       RA  ano_base    Fase  Fase_num            FaseIdeal_txt  FaseIdeal_num
0    RA-1      2022  FASE 7       7.0  Fase 8 (Universitários)              8
1    RA-2      2022  FASE 7       7.0           Fase 7 (3º EM)              7
2    RA-3      2022  FASE 7       7.0           Fase 7 (3º EM)              7
3    RA-4      2022  FASE 7       7.0           Fase 7 (3º EM)              7
4    RA-5      2022  FASE 7       7.0           Fase 7 (3º EM)              7
5    RA-6      2022  FASE 7       7.0  Fase 8 (Universitários)              8
6    RA-7      2022  FASE 7       7.0  Fase 8 (Universitários)              8
7    RA-8      2022  FASE 7       7.0  Fase 8 (Universitários)              8
8    RA-9      2022  FASE 7       7.0  Fase 8 (Universitários)              8
9   RA-10      2022  FASE 7       7.0  Fase 8 (Universitários)              8
10  RA-11      2022  FASE 7       7.0  Fase 8 (Universitários)              8
11  RA-12      2022  FASE 7       7.0           Fase 7 (3º EM)              7
12  RA-13      2022  FASE 7       7.0  Fase 8 (Universitários)              8
13  RA-14      2022  FASE 7       7.0  Fase 8 (Universitários)              8
14  RA-15      2022  FASE 7       7.0  Fase 8 (Universitários)              8
15  RA-16      2022  FASE 7       7.0  Fase 8 (Universitários)              8
16  RA-17      2022  FASE 7       7.0  Fase 8 (Universitários)              8
17  RA-18      2022  FASE 7       7.0  Fase 8 (Universitários)              8
18  RA-19      2022  FASE 7       7.0  Fase 8 (Universitários)              8
19  RA-20      2022  FASE 7       7.0  Fase 8 (Universitários)              8

In [49]:
# ============================================================
# BLOCO 3.5 — CONFERIR MAPEAMENTO DAS FASES DA P10
# Objetivo:
# - Identificar quais valores de Fase_num correspondem
#   a Quartzo, Ágata, Ametista e Topázio
# ============================================================

df_mapa_fases = (
    df_fase5_p10[["Fase", "Fase_num", "PEDRA_final", "PEDRA_fonte"]]
    .drop_duplicates()
    .sort_values(["Fase_num", "Fase"])
    .reset_index(drop=True)
)

print("Mapa de fases para conferência:")
display(df_mapa_fases)

Mapa de fases para conferência:

      Fase  Fase_num PEDRA_final PEDRA_fonte
0   FASE 0       0.0    Ametista  Pedra 2022
1   FASE 0       0.0     Topázio  Pedra 2022
2   FASE 0       0.0       Ágata  Pedra 2022
3   FASE 0       0.0     Quartzo  Pedra 2022
4     <NA>       0.0     Topázio  Pedra 2023
..     ...       ...         ...         ...
92    <NA>       7.0     Topázio  Pedra 2024
93    <NA>       7.0    Ametista  Pedra 2024
94    <NA>       7.0     Quartzo  Pedra 2024
95    <NA>       8.0         NaN         NaN
96  FASE 9       9.0     INCLUIR  Pedra 2024

[97 rows x 4 columns]

In [50]:
# ============================================================
# BLOCO 3.6 — CONTAR NULOS NA COLUNA Fase
# Objetivo:
# - Mostrar quantos registros da coluna Fase estão nulos
# ============================================================

qtd_nulos_fase = df_fase5_p10["Fase"].isna().sum()

print("Quantidade de nulos na coluna Fase:")
print(qtd_nulos_fase)

Quantidade de nulos na coluna Fase:
2132

In [52]:
# ============================================================
# BLOCO 3.7 — VERIFICAR Fase_num NAS LINHAS EM QUE Fase ESTÁ NULA
# Objetivo:
# - Filtrar os registros onde Fase está nula
# - Verificar se nessas linhas existe valor em Fase_num
# ============================================================

df_fase_nula = df_fase5_p10[df_fase5_p10["Fase"].isna()].copy()

print("Quantidade de linhas com Fase nula:")
print(len(df_fase_nula))

print("\nQuantidade de linhas com Fase nula e Fase_num preenchida:")
print(df_fase_nula["Fase_num"].notna().sum())

print("\nQuantidade de linhas com Fase nula e Fase_num também nula:")
print(df_fase_nula["Fase_num"].isna().sum())

print("\nValores únicos de Fase_num nas linhas com Fase nula:")
print(sorted(df_fase_nula["Fase_num"].dropna().unique()))

print("\nAmostra para conferência:")
display(df_fase_nula[["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]].head(20))

Quantidade de linhas com Fase nula:
2132

Quantidade de linhas com Fase nula e Fase_num preenchida:
2132

Quantidade de linhas com Fase nula e Fase_num também nula:
0

Valores únicos de Fase_num nas linhas com Fase nula:
[np.float64(0.0), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0)]

Amostra para conferência:

         RA  ano_base  Fase  Fase_num         FaseIdeal_txt  FaseIdeal_num
860  RA-861      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
861  RA-862      2023  <NA>       0.0  Fase 1 (3º e 4º ano)              1
862  RA-863      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
863  RA-864      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
864  RA-865      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
865  RA-866      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
866  RA-867      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
867  RA-868      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
868  RA-869      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
869  RA-870      2023  <NA>       0.0  Fase 1 (3º e 4º ano)              1
870  RA-871      2023  <NA>       0.0  Fase 1 (3º e 4º ano)              1
871  RA-872      2023  <NA>       0.0  Fase 2 (5º e 6º ano)              2
872  RA-873      2023  <NA>       0.0  Fase 2 (5º e 6º ano)              2
873  RA-874      2023  <NA>       0.0  Fase 1 (3º e 4º ano)              1
874  RA-875      2023  <NA>       0.0  Fase 1 (3º e 4º ano)              1
875  RA-876      2023  <NA>       0.0    ALFA (1º e 2º ano)              1
876  RA-877      2023  <NA>       0.0  Fase 1 (3º e 4º ano)              1
877  RA-878      2023  <NA>       0.0  Fase 2 (5º e 6º ano)              2
878  RA-879      2023  <NA>       0.0  Fase 1 (3º e 4º ano)              1
879  RA-880      2023  <NA>       0.0    ALFA (1º e 2º ano)              1

In [53]:
# ============================================================
# BLOCO 3.8  — PREENCHER Fase NULA COM BASE EM Fase_num
# Objetivo:
# - Identificar linhas em que Fase está nula
# - Preencher com "FASE X", onde X vem de Fase_num
# ============================================================

df_fase5_p10 = df_fase5_p10.copy()

mask_fase_nula = df_fase5_p10["Fase"].isna() & df_fase5_p10["Fase_num"].notna()

df_fase5_p10.loc[mask_fase_nula, "Fase"] = (
    "FASE " +
    df_fase5_p10.loc[mask_fase_nula, "Fase_num"]
    .astype("Int64")
    .astype("string")
)

print("Quantidade de linhas preenchidas em Fase:")
print(mask_fase_nula.sum())

print("\nAmostra para conferência:")
display(
    df_fase5_p10.loc[
        mask_fase_nula,
        ["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]
    ].head(20)
)

Quantidade de linhas preenchidas em Fase:
2132

Amostra para conferência:

         RA  ano_base    Fase  Fase_num         FaseIdeal_txt  FaseIdeal_num
860  RA-861      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
861  RA-862      2023  FASE 0       0.0  Fase 1 (3º e 4º ano)              1
862  RA-863      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
863  RA-864      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
864  RA-865      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
865  RA-866      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
866  RA-867      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
867  RA-868      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
868  RA-869      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
869  RA-870      2023  FASE 0       0.0  Fase 1 (3º e 4º ano)              1
870  RA-871      2023  FASE 0       0.0  Fase 1 (3º e 4º ano)              1
871  RA-872      2023  FASE 0       0.0  Fase 2 (5º e 6º ano)              2
872  RA-873      2023  FASE 0       0.0  Fase 2 (5º e 6º ano)              2
873  RA-874      2023  FASE 0       0.0  Fase 1 (3º e 4º ano)              1
874  RA-875      2023  FASE 0       0.0  Fase 1 (3º e 4º ano)              1
875  RA-876      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1
876  RA-877      2023  FASE 0       0.0  Fase 1 (3º e 4º ano)              1
877  RA-878      2023  FASE 0       0.0  Fase 2 (5º e 6º ano)              2
878  RA-879      2023  FASE 0       0.0  Fase 1 (3º e 4º ano)              1
879  RA-880      2023  FASE 0       0.0    ALFA (1º e 2º ano)              1

In [55]:
# ============================================================
# BLOCO 3.9 — MOSTRAR VALORES ORDENADOS DA COLUNA Fase
# Objetivo:
# - Exibir os valores distintos da coluna Fase em ordem
# ============================================================

valores_fase = sorted(df_fase5_p10["Fase"].dropna().astype(str).unique())

valores_fase_num = sorted(df_fase5_p10["Fase_num"].dropna().astype(str).unique())

valores_FaseIdeal_txt = sorted(df_fase5_p10["FaseIdeal_txt"].dropna().astype(str).unique())

valores_FaseIdeal_num = sorted(df_fase5_p10["FaseIdeal_num"].dropna().astype(str).unique())

print("Valores distintos da coluna Fase:")
print(valores_fase)

print("Valores distintos da coluna Fase_num:")
print(valores_fase_num)

print("Valores distintos da coluna FaseIdeal_txt:")
print(valores_FaseIdeal_txt)

print("Valores distintos da coluna FaseIdeal_num:")
print(valores_FaseIdeal_num)

Valores distintos da coluna Fase:
['FASE 0', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', 'FASE 8', 'FASE 9']
Valores distintos da coluna Fase_num:
['0.0', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0']
Valores distintos da coluna FaseIdeal_txt:
['ALFA (1º e 2º ano)', 'ALFA (2º e 3º ano)', 'Fase 1 (3º e 4º ano)', 'Fase 1 (4º ano)', 'Fase 2 (5º e 6º ano)', 'Fase 3 (7º e 8º ano)', 'Fase 4 (9º ano)', 'Fase 5 (1º EM)', 'Fase 6 (2º EM)', 'Fase 7 (3º EM)', 'Fase 8 (Universitários)']
Valores distintos da coluna FaseIdeal_num:
['1', '2', '3', '4', '5', '6', '7', '8']

In [56]:
# ============================================================
# BLOCO 3.10 — PADRONIZAR FaseIdeal_txt
# Objetivo:
# - Unificar categorias equivalentes em FaseIdeal_txt
# ============================================================

df_fase5_p10 = df_fase5_p10.copy()

mapa_faseideal_txt = {
    "ALFA (2º e 3º ano)": "ALFA (1º e 2º ano)",
    "Fase 1 (4º ano)": "Fase 1 (3º e 4º ano)"
}

df_fase5_p10["FaseIdeal_txt"] = df_fase5_p10["FaseIdeal_txt"].replace(mapa_faseideal_txt)

print("Valores únicos atualizados de FaseIdeal_txt:")
print(sorted(df_fase5_p10["FaseIdeal_txt"].dropna().unique()))

print("\nContagem por FaseIdeal_txt:")
print(df_fase5_p10["FaseIdeal_txt"].value_counts(dropna=False).sort_index())

Valores únicos atualizados de FaseIdeal_txt:
['ALFA (1º e 2º ano)', 'Fase 1 (3º e 4º ano)', 'Fase 2 (5º e 6º ano)', 'Fase 3 (7º e 8º ano)', 'Fase 4 (9º ano)', 'Fase 5 (1º EM)', 'Fase 6 (2º EM)', 'Fase 7 (3º EM)', 'Fase 8 (Universitários)']

Contagem por FaseIdeal_txt:
FaseIdeal_txt
ALFA (1º e 2º ano)         236
Fase 1 (3º e 4º ano)       386
Fase 2 (5º e 6º ano)       745
Fase 3 (7º e 8º ano)       644
Fase 4 (9º ano)            271
Fase 5 (1º EM)             224
Fase 6 (2º EM)             177
Fase 7 (3º EM)             147
Fase 8 (Universitários)    200
Name: count, dtype: int64

In [57]:
# ============================================================
# BLOCO 3.11 — VERIFICAR NULOS EM FaseIdeal_txt E FaseIdeal_num
# Objetivo:
# - Mostrar a quantidade de nulos nas colunas
#   FaseIdeal_txt e FaseIdeal_num
# ============================================================

print("Quantidade de nulos em FaseIdeal_txt:")
print(df_fase5_p10["FaseIdeal_txt"].isna().sum())

print("\nQuantidade de nulos em FaseIdeal_num:")
print(df_fase5_p10["FaseIdeal_num"].isna().sum())

Quantidade de nulos em FaseIdeal_txt:
0

Quantidade de nulos em FaseIdeal_num:
0

In [58]:
# ============================================================
# BLOCO 4 — CONTAGEM DA COLUNA PEDRA_final
# Objetivo:
# - Mostrar a quantidade de registros por valor de PEDRA_final
# - Incluir valores nulos na contagem
# ============================================================

print("Contagem de registros por PEDRA_final:")
print(df_p10["PEDRA_final"].value_counts(dropna=False))

Contagem de registros por PEDRA_final:
PEDRA_final
Ametista    1120
Topázio      688
Agata        471
Quartzo      316
Ágata        250
NaN          147
INCLUIR       38
Name: count, dtype: int64

In [59]:
# ============================================================
# BLOCO 4.1 — CONSULTA DAS COLUNAS RELACIONADAS A PEDRA
# Objetivo:
# - localizar todas as colunas com "PEDRA" no nome
# - exibir essas colunas em uma amostra da base
# ============================================================

colunas_pedra = [c for c in df_fase5_p10.columns if "PEDRA" in c.upper()]

print("Quantidade de colunas com referência a PEDRA:", len(colunas_pedra))
print("\nColunas encontradas:")
for c in colunas_pedra:
    print("-", c)

print("\nAmostra das colunas de PEDRA:")
display(df_fase5_p10[colunas_pedra].head(10))

Quantidade de colunas com referência a PEDRA: 8

Colunas encontradas:
- Pedra 20
- Pedra 21
- Pedra 22
- Pedra 2023
- Pedra 23
- Pedra 2024
- PEDRA_final
- PEDRA_fonte

Amostra das colunas de PEDRA:

,Pedra 20,Pedra 21,Pedra 22,Pedra 2023,Pedra 23,Pedra 2024,PEDRA_final,PEDRA_fonte
0,Ametista,Ametista,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
1,Ametista,Ametista,Ametista,NaN,NaN,NaN,Ametista,Pedra 2022
2,Ametista,Ametista,Ágata,NaN,NaN,NaN,Ágata,Pedra 2022
3,Ametista,Ametista,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
4,Ametista,Ametista,Ametista,NaN,NaN,NaN,Ametista,Pedra 2022
5,NaN,Ágata,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
6,Ametista,Ametista,Ágata,NaN,NaN,NaN,Ágata,Pedra 2022
7,Quartzo,Ágata,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
8,Ametista,Ametista,Topázio,NaN,NaN,NaN,Topázio,Pedra 2022
9,NaN,Ágata,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022

In [83]:
# ============================================================
# BLOCO 4.1.1 — RENOMEAR "Pedra 2024" PARA "Pedra 24"
# Objetivo:
# - padronizar o nome da coluna de 2024
# - manter o mesmo padrão das colunas Pedra 22 e Pedra 23
# ============================================================

df_fase5_p10 = df_fase5_p10.copy()

if "Pedra 2024" in df_fase5_p10.columns:
    df_fase5_p10 = df_fase5_p10.rename(columns={"Pedra 2024": "Pedra 24"})
    print('Coluna "Pedra 2024" renomeada para "Pedra 24".')
else:
    print('A coluna "Pedra 2024" não foi encontrada.')

print("\nColunas de pedra após ajuste:")
colunas_pedra = [c for c in df_fase5_p10.columns if "PEDRA" in c.upper()]
print(sorted(colunas_pedra))

Coluna "Pedra 2024" renomeada para "Pedra 24".

Colunas de pedra após ajuste:
['PEDRA_final', 'PEDRA_fonte', 'Pedra 20', 'Pedra 2023', 'Pedra 21', 'Pedra 22', 'Pedra 23', 'Pedra 24']

In [77]:
# ============================================================
# BLOCO 4.2 — VALIDAR PEDRA 23 x PEDRA 2023 POR RA
# Objetivo:
# - consolidar por RA
# - trazer Pedra 23 e Pedra 2023 lado a lado
# - classificar a situação entre as duas colunas
# ============================================================

df_tmp = df_fase5_p10[["RA", "Pedra 23", "Pedra 2023"]].copy()

# padroniza texto
for c in ["Pedra 23", "Pedra 2023"]:
    df_tmp[c] = df_tmp[c].astype("string").str.strip()

# função para pegar o primeiro valor não nulo
def primeiro_nao_nulo(serie):
    serie = serie.dropna()
    return serie.iloc[0] if len(serie) > 0 else pd.NA

# consolida por RA
df_validacao_2023 = (
    df_tmp
    .groupby("RA", as_index=False)
    .agg({
        "Pedra 23": primeiro_nao_nulo,
        "Pedra 2023": primeiro_nao_nulo
    })
)

# coluna de validação
def validar_pedra_2023(row):
    p23 = row["Pedra 23"]
    p2023 = row["Pedra 2023"]

    if pd.isna(p23) and pd.isna(p2023):
        return "AMBAS_VAZIAS"
    elif pd.notna(p23) and pd.notna(p2023) and p23 == p2023:
        return "IGUAL"
    elif pd.notna(p23) and pd.isna(p2023):
        return "COMPLEMENTAR_SO_PEDRA23"
    elif pd.isna(p23) and pd.notna(p2023):
        return "COMPLEMENTAR_SO_PEDRA2023"
    else:
        return "CONFLITO"

df_validacao_2023["validacao"] = df_validacao_2023.apply(validar_pedra_2023, axis=1)

print("Resumo da validação por RA:")
display(
    df_validacao_2023["validacao"]
    .value_counts(dropna=False)
    .rename_axis("validacao")
    .reset_index(name="quantidade")
)

print("\nAmostra da base consolidada por RA:")
display(df_validacao_2023.head(30))

Resumo da validação por RA:

                   validacao  quantidade
0               AMBAS_VAZIAS         730
1                      IGUAL         690
2  COMPLEMENTAR_SO_PEDRA2023         241

Amostra da base consolidada por RA:

         RA  Pedra 23 Pedra 2023                  validacao
0      RA-1      <NA>       <NA>               AMBAS_VAZIAS
1     RA-10      <NA>       <NA>               AMBAS_VAZIAS
2    RA-100      <NA>       <NA>               AMBAS_VAZIAS
3   RA-1000  Ametista   Ametista                      IGUAL
4   RA-1001   Topázio    Topázio                      IGUAL
5   RA-1002  Ametista   Ametista                      IGUAL
6   RA-1003  Ametista   Ametista                      IGUAL
7   RA-1004   Topázio    Topázio                      IGUAL
8   RA-1005      <NA>    Topázio  COMPLEMENTAR_SO_PEDRA2023
9   RA-1006   Topázio    Topázio                      IGUAL
10  RA-1007      <NA>    Topázio  COMPLEMENTAR_SO_PEDRA2023
11  RA-1008   Topázio    Topázio                      IGUAL
12  RA-1009  Ametista   Ametista                      IGUAL
13   RA-101      <NA>       <NA>               AMBAS_VAZIAS
14  RA-1010      <NA>    Topázio  COMPLEMENTAR_SO_PEDRA2023
15  RA-1011      <NA>   Ametista  COMPLEMENTAR_SO_PEDRA2023
16  RA-1012  Ametista   Ametista                      IGUAL
17  RA-1013  Ametista   Ametista                      IGUAL
18  RA-1014   Topázio    Topázio                      IGUAL
19  RA-1015  Ametista   Ametista                      IGUAL
20  RA-1016      <NA>   Ametista  COMPLEMENTAR_SO_PEDRA2023
21  RA-1017     Agata      Agata                      IGUAL
22  RA-1018     Agata      Agata                      IGUAL
23  RA-1019  Ametista   Ametista                      IGUAL
24   RA-102      <NA>       <NA>               AMBAS_VAZIAS
25  RA-1020  Ametista   Ametista                      IGUAL
26  RA-1021     Agata      Agata                      IGUAL
27  RA-1022  Ametista   Ametista                      IGUAL
28  RA-1023   Topázio    Topázio                      IGUAL
29  RA-1024  Ametista   Ametista                      IGUAL

In [22]:
# ============================================================
# BLOCO 4.3 — PREENCHER PEDRA 23 COM PEDRA 2023
# Objetivo:
# - completar a coluna Pedra 23
# - usar Pedra 2023 apenas quando Pedra 23 estiver nula
# ============================================================

df_fase5_p10 = df_fase5_p10.copy()

df_fase5_p10["Pedra 23"] = df_fase5_p10["Pedra 23"].fillna(df_fase5_p10["Pedra 2023"])

print("Nulos em Pedra 23 após preenchimento:")
print(df_fase5_p10["Pedra 23"].isna().sum())

print("\nAmostra das colunas após ajuste:")
display(df_fase5_p10[["RA", "Pedra 23", "Pedra 2023"]].head(20))

Nulos em Pedra 23 após preenchimento:
1409

Amostra das colunas após ajuste:

       RA Pedra 23 Pedra 2023
0    RA-1      NaN        NaN
1    RA-2      NaN        NaN
2    RA-3      NaN        NaN
3    RA-4      NaN        NaN
4    RA-5      NaN        NaN
5    RA-6      NaN        NaN
6    RA-7      NaN        NaN
7    RA-8      NaN        NaN
8    RA-9      NaN        NaN
9   RA-10      NaN        NaN
10  RA-11      NaN        NaN
11  RA-12      NaN        NaN
12  RA-13      NaN        NaN
13  RA-14      NaN        NaN
14  RA-15      NaN        NaN
15  RA-16      NaN        NaN
16  RA-17      NaN        NaN
17  RA-18      NaN        NaN
18  RA-19      NaN        NaN
19  RA-20      NaN        NaN

In [61]:
# ============================================================
# BLOCO 4.4 — VALIDAR PEDRA 23 x PEDRA 2023 POR RA
# Objetivo:
# - consolidar por RA
# - trazer Pedra 23 e Pedra 2023 lado a lado
# - classificar a situação entre as duas colunas
# ============================================================

df_tmp = df_fase5_p10[["RA", "Pedra 23", "Pedra 2023"]].copy()

# padroniza texto
for c in ["Pedra 23", "Pedra 2023"]:
    df_tmp[c] = df_tmp[c].astype("string").str.strip()

# função para pegar o primeiro valor não nulo
def primeiro_nao_nulo(serie):
    serie = serie.dropna()
    return serie.iloc[0] if len(serie) > 0 else pd.NA

# consolida por RA
df_validacao_2023 = (
    df_tmp
    .groupby("RA", as_index=False)
    .agg({
        "Pedra 23": primeiro_nao_nulo,
        "Pedra 2023": primeiro_nao_nulo
    })
)

# coluna de validação
def validar_pedra_2023(row):
    p23 = row["Pedra 23"]
    p2023 = row["Pedra 2023"]

    if pd.isna(p23) and pd.isna(p2023):
        return "AMBAS_VAZIAS"
    elif pd.notna(p23) and pd.notna(p2023) and p23 == p2023:
        return "IGUAL"
    elif pd.notna(p23) and pd.isna(p2023):
        return "COMPLEMENTAR_SO_PEDRA23"
    elif pd.isna(p23) and pd.notna(p2023):
        return "COMPLEMENTAR_SO_PEDRA2023"
    else:
        return "CONFLITO"

df_validacao_2023["validacao"] = df_validacao_2023.apply(validar_pedra_2023, axis=1)

print("Resumo da validação por RA:")
display(
    df_validacao_2023["validacao"]
    .value_counts(dropna=False)
    .rename_axis("validacao")
    .reset_index(name="quantidade")
)

Resumo da validação por RA:

                   validacao  quantidade
0               AMBAS_VAZIAS         730
1                      IGUAL         690
2  COMPLEMENTAR_SO_PEDRA2023         241

In [85]:
# ============================================================
# BLOCO 5 — TRANSFORMAR AS PEDRAS EM BASE LONGA (2022 A 2024)
# Objetivo:
# - reorganizar as colunas de pedra em formato longitudinal
# - considerar apenas o período oficial do Datathon: 2022 a 2024
# - manter apenas registros com pedra preenchida
# ============================================================

df_base = df_fase5_p10.copy()

colunas_pedra = {
    "Pedra 22": 1,
    "Pedra 23": 2,
    "Pedra 24": 3
}

bases = []

for col, ordem in colunas_pedra.items():
    df_temp = df_base[["RA", col]].copy()
    df_temp = df_temp.rename(columns={col: "pedra"})
    df_temp["pedra_referencia"] = col
    df_temp["ordem_referencia"] = ordem
    bases.append(df_temp)

df_pedra_long = pd.concat(bases, ignore_index=True)

df_pedra_long = df_pedra_long[["RA", "pedra_referencia", "ordem_referencia", "pedra"]].copy()

# remove linhas sem pedra
df_pedra_long = df_pedra_long[df_pedra_long["pedra"].notna()].copy()

print("Dimensão da base longa:")
print(df_pedra_long.shape)

print("\nAmostra:")
display(df_pedra_long.tail(20))

print("\nNulos por coluna:")
print(df_pedra_long.isna().sum())

Dimensão da base longa:
(3714, 4)

Amostra:

           RA pedra_referencia  ordem_referencia    pedra
9070  RA-1649         Pedra 24                 3  INCLUIR
9071  RA-1650         Pedra 24                 3  INCLUIR
9072  RA-1651         Pedra 24                 3  INCLUIR
9073  RA-1652         Pedra 24                 3  INCLUIR
9074  RA-1653         Pedra 24                 3  INCLUIR
9075  RA-1654         Pedra 24                 3  INCLUIR
9076  RA-1655         Pedra 24                 3  INCLUIR
9077  RA-1656         Pedra 24                 3  INCLUIR
9078  RA-1254         Pedra 24                 3  INCLUIR
9079  RA-1233         Pedra 24                 3  INCLUIR
9080  RA-1232         Pedra 24                 3  INCLUIR
9081  RA-1231         Pedra 24                 3  INCLUIR
9082  RA-1238         Pedra 24                 3  INCLUIR
9083  RA-1267         Pedra 24                 3  INCLUIR
9084  RA-1657         Pedra 24                 3  INCLUIR
9085  RA-1658         Pedra 24                 3  INCLUIR
9086  RA-1659         Pedra 24                 3  INCLUIR
9087  RA-1252         Pedra 24                 3  INCLUIR
9088  RA-1660         Pedra 24                 3  INCLUIR
9089  RA-1661         Pedra 24                 3  INCLUIR

Nulos por coluna:
RA                  0
pedra_referencia    0
ordem_referencia    0
pedra               0
dtype: int64

In [86]:
# ============================================================
# BLOCO 5.1 — BASE LONGA DE PEDRAS (2022 A 2024) COM PADRONIZAÇÃO E SCORE
# Objetivo:
# - considerar apenas 2022, 2023 e 2024
# - padronizar nomes das pedras
# - remover valores inválidos
# - criar score ordinal para análise de evolução
# ============================================================

df_base = df_fase5_p10.copy()

colunas_pedra = {
    "Pedra 22": 1,
    "Pedra 23": 2,
    "Pedra 24": 3
}

bases = []

for col, ordem in colunas_pedra.items():
    df_temp = df_base[["RA", col]].copy()
    df_temp = df_temp.rename(columns={col: "pedra"})
    df_temp["pedra_referencia"] = col
    df_temp["ordem_referencia"] = ordem
    bases.append(df_temp)

df_pedra_long = pd.concat(bases, ignore_index=True)

df_pedra_long = df_pedra_long[["RA", "pedra_referencia", "ordem_referencia", "pedra"]].copy()

df_pedra_long["pedra"] = df_pedra_long["pedra"].astype("string").str.strip()

df_pedra_long["pedra"] = df_pedra_long["pedra"].replace({
    "Agata": "Ágata",
    "AGATA": "Ágata",
    "Topazio": "Topázio",
    "TOPAZIO": "Topázio",
    "INCLUIR": pd.NA
})

df_pedra_long = df_pedra_long[df_pedra_long["pedra"].notna()].copy()

mapa_score_pedra = {
    "Quartzo": 1,
    "Ágata": 2,
    "Ametista": 3,
    "Topázio": 4
}

df_pedra_long["score_pedra"] = df_pedra_long["pedra"].map(mapa_score_pedra)

print("Dimensão da base longa:")
print(df_pedra_long.shape)

print("\nAmostra:")
display(df_pedra_long.tail(20))

print("\nDistribuição das pedras:")
display(
    df_pedra_long["pedra"]
    .value_counts(dropna=False)
    .rename_axis("pedra")
    .reset_index(name="quantidade")
)

print("\nNulos em score_pedra:")
print(df_pedra_long["score_pedra"].isna().sum())

Dimensão da base longa:
(3676, 5)

Amostra:

           RA pedra_referencia  ordem_referencia     pedra  score_pedra
8968   RA-153         Pedra 24                 3   Quartzo            1
8969  RA-1226         Pedra 24                 3  Ametista            3
8970    RA-93         Pedra 24                 3   Topázio            4
8971   RA-119         Pedra 24                 3   Topázio            4
8972   RA-241         Pedra 24                 3   Topázio            4
8973   RA-242         Pedra 24                 3   Topázio            4
8974    RA-52         Pedra 24                 3   Topázio            4
8975  RA-1227         Pedra 24                 3   Quartzo            1
8976   RA-245         Pedra 24                 3   Topázio            4
8977   RA-246         Pedra 24                 3   Quartzo            1
8978  RA-1228         Pedra 24                 3   Quartzo            1
8979  RA-1229         Pedra 24                 3   Quartzo            1
8980    RA-98         Pedra 24                 3   Topázio            4
8981   RA-277         Pedra 24                 3   Topázio            4
8982   RA-172         Pedra 24                 3   Topázio            4
8983   RA-291         Pedra 24                 3  Ametista            3
8984    RA-86         Pedra 24                 3  Ametista            3
8985   RA-143         Pedra 24                 3  Ametista            3
8986   RA-166         Pedra 24                 3   Topázio            4
8987   RA-191         Pedra 24                 3  Ametista            3

Distribuição das pedras:

      pedra  quantidade
0  Ametista        1529
1     Ágata         910
2   Topázio         867
3   Quartzo         370

Nulos em score_pedra:
0

In [87]:
# ============================================================
# BLOCO 5.2 — CONSULTA DAS PEDRAS POR RA COM ANÁLISE DOS SCORES
# Objetivo:
# - montar uma visão por aluno com as pedras de 2022, 2023 e 2024
# - converter as pedras em scores ordinais
# - classificar a trajetória do aluno no período
# ============================================================

df_consulta_pedras = df_fase5_p10.copy()

colunas = ["RA", "Pedra 22", "Pedra 23", "Pedra 24"]
df_consulta_pedras = df_consulta_pedras[colunas].copy()

# padroniza texto
for c in ["Pedra 22", "Pedra 23", "Pedra 24"]:
    df_consulta_pedras[c] = df_consulta_pedras[c].astype("string").str.strip()

for c in ["Pedra 22", "Pedra 23", "Pedra 24"]:
    df_consulta_pedras[c] = df_consulta_pedras[c].replace(mapa_padrao)

# função para pegar o primeiro valor não nulo por RA
def primeiro_nao_nulo(s):
    s = s.dropna()
    return s.iloc[0] if len(s) > 0 else pd.NA

# consolida por RA
df_consulta_pedras = (
    df_consulta_pedras
    .groupby("RA", as_index=False)
    .agg({
        "Pedra 22": primeiro_nao_nulo,
        "Pedra 23": primeiro_nao_nulo,
        "Pedra 24": primeiro_nao_nulo
    })
)

# score ordinal das pedras
mapa_score = {
    "Quartzo": 1,
    "Ágata": 2,
    "Ametista": 3,
    "Topázio": 4
}

df_consulta_pedras["score_22"] = df_consulta_pedras["Pedra 22"].map(mapa_score)
df_consulta_pedras["score_23"] = df_consulta_pedras["Pedra 23"].map(mapa_score)
df_consulta_pedras["score_24"] = df_consulta_pedras["Pedra 24"].map(mapa_score)

# análise da trajetória
def analisar_trajetoria(row):
    s22 = row["score_22"]
    s23 = row["score_23"]
    s24 = row["score_24"]

    scores = [x for x in [s22, s23, s24] if pd.notna(x)]

    if len(scores) < 2:
        return "Informação insuficiente"

    if scores == sorted(scores) and len(set(scores)) == 1:
        return "Estável"

    if scores == sorted(scores) and len(set(scores)) > 1:
        return "Melhora consistente"

    if scores == sorted(scores, reverse=True) and len(set(scores)) > 1:
        return "Piora consistente"

    if scores[-1] > scores[0]:
        return "Oscilou, mas melhorou no final"

    if scores[-1] < scores[0]:
        return "Oscilou, mas piorou no final"

    return "Oscilou e terminou estável"

df_consulta_pedras["analise"] = df_consulta_pedras.apply(analisar_trajetoria, axis=1)

print("Dimensão da base final:")
print(df_consulta_pedras.shape)

print("\nAmostra:")
display(df_consulta_pedras.head(20))

print("\nResumo da análise:")
display(
    df_consulta_pedras["analise"]
    .value_counts(dropna=False)
    .rename_axis("analise")
    .reset_index(name="quantidade")
)

Dimensão da base final:
(1661, 8)

Amostra:

,RA,Pedra 22,Pedra 23,Pedra 24,score_22,score_23,score_24,analise
0,RA-1,Quartzo,<NA>,<NA>,1.0,NaN,NaN,Informação insuficiente
1,RA-10,Quartzo,<NA>,<NA>,1.0,NaN,NaN,Informação insuficiente
2,RA-100,Ametista,<NA>,<NA>,3.0,NaN,NaN,Informação insuficiente
3,RA-1000,<NA>,Ametista,Topázio,NaN,3.0,4.0,Melhora consistente
4,RA-1001,<NA>,Topázio,Ametista,NaN,4.0,3.0,Piora consistente
5,RA-1002,<NA>,Ametista,Ametista,NaN,3.0,3.0,Estável
6,RA-1003,<NA>,Ametista,Ametista,NaN,3.0,3.0,Estável
7,RA-1004,<NA>,Topázio,Ametista,NaN,4.0,3.0,Piora consistente
8,RA-1005,<NA>,<NA>,<NA>,NaN,NaN,NaN,Informação insuficiente
9,RA-1006,<NA>,Topázio,Ametista,NaN,4.0,3.0,Piora consistente
10,RA-1007,<NA>,<NA>,<NA>,NaN,NaN,NaN,Informação insuficiente
11,RA-1008,<NA>,Topázio,Ágata,NaN,4.0,2.0,Piora consistente
12,RA-1009,<NA>,Ametista,Ágata,NaN,3.0,2.0,Piora consistente
13,RA-101,Ametista,<NA>,<NA>,3.0,NaN,NaN,Informação insuficiente
14,RA-1010,<NA>,<NA>,<NA>,NaN,NaN,NaN,Informação insuficiente
15,RA-1011,<NA>,<NA>,<NA>,NaN,NaN,NaN,Informação insuficiente
16,RA-1012,<NA>,Ametista,Topázio,NaN,3.0,4.0,Melhora consistente
17,RA-1013,<NA>,Ametista,Quartzo,NaN,3.0,1.0,Piora consistente
18,RA-1014,<NA>,Topázio,Ágata,NaN,4.0,2.0,Piora consistente
19,RA-1015,<NA>,Ametista,Ágata,NaN,3.0,2.0,Piora consistente

Resumo da análise:

                          analise  quantidade
0         Informação insuficiente         963
1                         Estável         253
2               Piora consistente         178
3             Melhora consistente         172
4      Oscilou e terminou estável          77
5    Oscilou, mas piorou no final          10
6  Oscilou, mas melhorou no final           8

In [88]:
# ============================================================
# BLOCO 6 — BASE FINAL DA P10 COM ELEGIBILIDADE
# Objetivo:
# - contar quantos pontos válidos cada aluno possui entre 2022 e 2024
# - definir se o aluno é elegível para análise longitudinal
# - manter a base final pronta para exportação e uso no Power BI
# ============================================================

df_p10_base_final = df_consulta_pedras.copy()

# quantidade de pontos válidos por aluno
df_p10_base_final["qtd_pontos_validos"] = (
    df_p10_base_final[["score_22", "score_23", "score_24"]]
    .notna()
    .sum(axis=1)
)

# regra de elegibilidade
df_p10_base_final["elegivel_analise"] = np.where(
    df_p10_base_final["qtd_pontos_validos"] >= 2,
    "Sim",
    "Não"
)

# análise resumida
def resumir_analise(valor):
    if valor in ["Melhora consistente", "Oscilou, mas melhorou no final"]:
        return "Melhorou"
    elif valor in ["Estável", "Oscilou e terminou estável"]:
        return "Estável"
    elif valor in ["Piora consistente", "Oscilou, mas piorou no final"]:
        return "Piorou"
    else:
        return "Informação insuficiente"

df_p10_base_final["analise_resumida"] = df_p10_base_final["analise"].apply(resumir_analise)

# organiza colunas finais
df_p10_base_final = df_p10_base_final[
    [
        "RA",
        "Pedra 22",
        "Pedra 23",
        "Pedra 24",
        "score_22",
        "score_23",
        "score_24",
        "qtd_pontos_validos",
        "elegivel_analise",
        "analise",
        "analise_resumida"
    ]
].copy()

print("Dimensão da base final da P10:")
print(df_p10_base_final.shape)

print("\nAmostra:")
display(df_p10_base_final.head(20))

print("\nResumo da elegibilidade:")
display(
    df_p10_base_final["elegivel_analise"]
    .value_counts(dropna=False)
    .rename_axis("elegivel_analise")
    .reset_index(name="quantidade")
)

print("\nResumo da análise resumida:")
display(
    df_p10_base_final["analise_resumida"]
    .value_counts(dropna=False)
    .rename_axis("analise_resumida")
    .reset_index(name="quantidade")
)

Dimensão da base final da P10:
(1661, 11)

Amostra:

,RA,Pedra 22,Pedra 23,Pedra 24,score_22,score_23,score_24,qtd_pontos_validos,elegivel_analise,analise,analise_resumida
0,RA-1,Quartzo,<NA>,<NA>,1.0,NaN,NaN,1,Não,Informação insuficiente,Informação insuficiente
1,RA-10,Quartzo,<NA>,<NA>,1.0,NaN,NaN,1,Não,Informação insuficiente,Informação insuficiente
2,RA-100,Ametista,<NA>,<NA>,3.0,NaN,NaN,1,Não,Informação insuficiente,Informação insuficiente
3,RA-1000,<NA>,Ametista,Topázio,NaN,3.0,4.0,2,Sim,Melhora consistente,Melhorou
4,RA-1001,<NA>,Topázio,Ametista,NaN,4.0,3.0,2,Sim,Piora consistente,Piorou
5,RA-1002,<NA>,Ametista,Ametista,NaN,3.0,3.0,2,Sim,Estável,Estável
6,RA-1003,<NA>,Ametista,Ametista,NaN,3.0,3.0,2,Sim,Estável,Estável
7,RA-1004,<NA>,Topázio,Ametista,NaN,4.0,3.0,2,Sim,Piora consistente,Piorou
8,RA-1005,<NA>,<NA>,<NA>,NaN,NaN,NaN,0,Não,Informação insuficiente,Informação insuficiente
9,RA-1006,<NA>,Topázio,Ametista,NaN,4.0,3.0,2,Sim,Piora consistente,Piorou
10,RA-1007,<NA>,<NA>,<NA>,NaN,NaN,NaN,0,Não,Informação insuficiente,Informação insuficiente
11,RA-1008,<NA>,Topázio,Ágata,NaN,4.0,2.0,2,Sim,Piora consistente,Piorou
12,RA-1009,<NA>,Ametista,Ágata,NaN,3.0,2.0,2,Sim,Piora consistente,Piorou
13,RA-101,Ametista,<NA>,<NA>,3.0,NaN,NaN,1,Não,Informação insuficiente,Informação insuficiente
14,RA-1010,<NA>,<NA>,<NA>,NaN,NaN,NaN,0,Não,Informação insuficiente,Informação insuficiente
15,RA-1011,<NA>,<NA>,<NA>,NaN,NaN,NaN,0,Não,Informação insuficiente,Informação insuficiente
16,RA-1012,<NA>,Ametista,Topázio,NaN,3.0,4.0,2,Sim,Melhora consistente,Melhorou
17,RA-1013,<NA>,Ametista,Quartzo,NaN,3.0,1.0,2,Sim,Piora consistente,Piorou
18,RA-1014,<NA>,Topázio,Ágata,NaN,4.0,2.0,2,Sim,Piora consistente,Piorou
19,RA-1015,<NA>,Ametista,Ágata,NaN,3.0,2.0,2,Sim,Piora consistente,Piorou

Resumo da elegibilidade:

  elegivel_analise  quantidade
0              Não         963
1              Sim         698

Resumo da análise resumida:

          analise_resumida  quantidade
0  Informação insuficiente         963
1                  Estável         330
2                   Piorou         188
3                 Melhorou         180

In [89]:
# ============================================================
# BLOCO 6.1 — GERAR RESUMO EXECUTIVO DA P10
# Objetivo:
# - consolidar a análise da P10 em contagem e percentual
# - separar base total e base elegível para análise longitudinal
# - gerar tabelas prontas para uso no Power BI
# ============================================================

# ------------------------------
# 1. Resumo da base total
# ------------------------------
df_p10_resumo_total = (
    df_p10_base_final["analise_resumida"]
    .value_counts(dropna=False)
    .rename_axis("analise_resumida")
    .reset_index(name="quantidade")
)

total_alunos = df_p10_resumo_total["quantidade"].sum()

df_p10_resumo_total["percentual"] = (
    df_p10_resumo_total["quantidade"] / total_alunos * 100
).round(2)

df_p10_resumo_total["base"] = "Base total 2022-2024"

df_p10_resumo_total = df_p10_resumo_total[
    ["base", "analise_resumida", "quantidade", "percentual"]
].copy()

print("Resumo executivo — base total:")
display(df_p10_resumo_total)

# ------------------------------
# 2. Resumo apenas da base elegível
# ------------------------------
df_p10_elegiveis = df_p10_base_final[
    df_p10_base_final["elegivel_analise"] == "Sim"
].copy()

df_p10_resumo_elegiveis = (
    df_p10_elegiveis["analise_resumida"]
    .value_counts(dropna=False)
    .rename_axis("analise_resumida")
    .reset_index(name="quantidade")
)

total_elegiveis = df_p10_resumo_elegiveis["quantidade"].sum()

df_p10_resumo_elegiveis["percentual"] = (
    df_p10_resumo_elegiveis["quantidade"] / total_elegiveis * 100
).round(2)

df_p10_resumo_elegiveis["base"] = "Base elegível"

df_p10_resumo_elegiveis = df_p10_resumo_elegiveis[
    ["base", "analise_resumida", "quantidade", "percentual"]
].copy()

print("\nResumo executivo — base elegível:")
display(df_p10_resumo_elegiveis)

# ------------------------------
# 3. Resumo consolidado
# ------------------------------
df_p10_resumo_analise = pd.concat(
    [df_p10_resumo_total, df_p10_resumo_elegiveis],
    ignore_index=True
)

print("\nResumo executivo consolidado:")
display(df_p10_resumo_analise)

# ------------------------------
# 4. Resumo da elegibilidade
# ------------------------------
df_p10_resumo_elegibilidade = (
    df_p10_base_final["elegivel_analise"]
    .value_counts(dropna=False)
    .rename_axis("elegivel_analise")
    .reset_index(name="quantidade")
)

total_base = df_p10_resumo_elegibilidade["quantidade"].sum()

df_p10_resumo_elegibilidade["percentual"] = (
    df_p10_resumo_elegibilidade["quantidade"] / total_base * 100
).round(2)

print("\nResumo da elegibilidade:")
display(df_p10_resumo_elegibilidade)

Resumo executivo — base total:

                   base         analise_resumida  quantidade  percentual
0  Base total 2022-2024  Informação insuficiente         963       57.98
1  Base total 2022-2024                  Estável         330       19.87
2  Base total 2022-2024                   Piorou         188       11.32
3  Base total 2022-2024                 Melhorou         180       10.84

Resumo executivo — base elegível:

            base analise_resumida  quantidade  percentual
0  Base elegível          Estável         330       47.28
1  Base elegível           Piorou         188       26.93
2  Base elegível         Melhorou         180       25.79

Resumo executivo consolidado:

                   base         analise_resumida  quantidade  percentual
0  Base total 2022-2024  Informação insuficiente         963       57.98
1  Base total 2022-2024                  Estável         330       19.87
2  Base total 2022-2024                   Piorou         188       11.32
3  Base total 2022-2024                 Melhorou         180       10.84
4         Base elegível                  Estável         330       47.28
5         Base elegível                   Piorou         188       26.93
6         Base elegível                 Melhorou         180       25.79

Resumo da elegibilidade:

  elegivel_analise  quantidade  percentual
0              Não         963       57.98
1              Sim         698       42.02

## **RESUMO EXECUTIVO DA P10**

A Pergunta 10 busca verificar se os indicadores educacionais evidenciam melhora consistente ao longo do ciclo, nas diferentes fases representadas pelas pedras **Quartzo**, **Ágata**, **Ametista** e **Topázio**, confirmando o impacto real do programa.

Para responder a essa questão, foi construída uma análise longitudinal por aluno no período oficial do Datathon, considerando exclusivamente os anos de **2022, 2023 e 2024**, por meio das colunas **Pedra 22**, **Pedra 23** e **Pedra 24**.

As pedras foram convertidas em uma escala ordinal para permitir comparação objetiva entre os anos:

- **Quartzo = 1**
- **Ágata = 2**
- **Ametista = 3**
- **Topázio = 4**

Os registros com valor nulo e os casos classificados como **INCLUIR** foram desconsiderados na análise das trajetórias. Essa exclusão foi necessária porque, nessas situações, não havia informação válida suficiente para identificar com segurança a pedra correspondente e, portanto, não era possível atribuir um score confiável para comparação longitudinal.

Com base nessa escala, cada aluno foi classificado segundo sua trajetória no período, distinguindo situações de:

- **Melhora consistente**
- **Estabilidade**
- **Piora consistente**
- **Oscilação com melhora final**
- **Oscilação com piora final**
- **Oscilação com término estável**
- **Informação insuficiente**

Além da análise detalhada, foi gerado um resumo executivo com a consolidação dos resultados em categorias sintéticas, permitindo identificar o saldo geral das trajetórias dos alunos no ciclo 2022–2024.

Essa etapa é fundamental para responder à Pergunta 10, pois desloca a análise de uma fotografia isolada da pedra final para uma leitura de trajetória, tornando possível avaliar se houve avanço real, manutenção de desempenho ou regressão ao longo do período analisado.

O resultado dessa consolidação servirá como base para os visuais e indicadores do Power BI, especialmente para:

- distribuição dos alunos por tipo de trajetória
- percentual de melhora, estabilidade e piora
- leitura executiva sobre a efetividade do programa no ciclo analisado

Como limitação metodológica, destaca-se que alunos com quantidade insuficiente de registros válidos no período são classificados como **informação insuficiente**, não sendo interpretados como evidência de melhora, estabilidade ou piora.

### **Recorte temporal e elegibilidade da análise**

A análise principal da Pergunta 10 considera exclusivamente o período de **2022 a 2024**, em conformidade com o recorte oficial do Datathon. Para isso, foram utilizadas as colunas **Pedra 22**, **Pedra 23** e **Pedra 24**.

Dentro desse período, a base foi separada em dois conjuntos:

- **base total do recorte 2022–2024**: contempla todos os alunos com registros no período
- **amostra elegível para análise de trajetória**: contempla apenas os alunos com informações suficientes para comparação longitudinal entre os anos

Essa distinção é importante porque nem todos os alunos possuem registros válidos em quantidade suficiente para permitir classificação segura de melhora, estabilidade ou regressão. Nesses casos, o aluno permanece na base do período, mas é classificado como **informação insuficiente** na análise executiva.

In [95]:
# ============================================================
# BLOCO 7 — EXPORTAR AS BASES FINAIS DA P10 EM CSV E PARQUET
# Objetivo:
# - salvar as bases finais da Pergunta 10 na pasta data/processed
# - deixar os arquivos prontos para Git e Power BI
# ============================================================

import os

REPO_DIR = "/content/fase5"
out_dir = os.path.join(REPO_DIR, "data", "processed")
os.makedirs(out_dir, exist_ok=True)

# CSV
df_p10_base_final.to_csv(os.path.join(out_dir, "df_q10_base_final.csv"), index=False, encoding="utf-8")
df_p10_resumo_analise.to_csv(os.path.join(out_dir, "df_q10_resumo_analise.csv"), index=False, encoding="utf-8")
df_p10_resumo_elegibilidade.to_csv(os.path.join(out_dir, "df_q10_resumo_elegibilidade.csv"), index=False, encoding="utf-8")
df_pedra_long.to_csv(os.path.join(out_dir, "df_q10_pedra_long.csv"), index=False, encoding="utf-8")

# Parquet (se der erro: !pip install -q pyarrow)
df_p10_base_final.to_parquet(os.path.join(out_dir, "df_q10_base_final.parquet"), index=False)
df_p10_resumo_analise.to_parquet(os.path.join(out_dir, "df_q10_resumo_analise.parquet"), index=False)
df_p10_resumo_elegibilidade.to_parquet(os.path.join(out_dir, "df_q10_resumo_elegibilidade.parquet"), index=False)
df_pedra_long.to_parquet(os.path.join(out_dir, "df_q10_pedra_long.parquet"), index=False)

print("Arquivos gerados em:", out_dir)
print(sorted(os.listdir(out_dir)))

Arquivos gerados em: /content/fase5/data/processed
['df_fase5.csv', 'df_fase5.parquet', 'df_ian.csv', 'df_ian.parquet', 'df_ida_ano.csv', 'df_ida_ano.parquet', 'df_ida_fase.csv', 'df_ida_fase.parquet', 'df_q10_base_final.csv', 'df_q10_base_final.parquet', 'df_q10_pedra_long.csv', 'df_q10_pedra_long.parquet', 'df_q10_resumo_analise.csv', 'df_q10_resumo_analise.parquet', 'df_q10_resumo_elegibilidade.csv', 'df_q10_resumo_elegibilidade.parquet', 'df_q11A_perfis_alunos.csv', 'df_q11A_perfis_alunos.parquet', 'df_q11A_perfis_resumo.csv', 'df_q11A_perfis_resumo.parquet', 'df_q11B_flags_alunos.csv', 'df_q11B_flags_alunos.parquet', 'df_q11B_resumo.csv', 'df_q11B_resumo.parquet', 'df_q11C_alerta_precoce_alunos.csv', 'df_q11C_alerta_precoce_alunos.parquet', 'df_q11C_resumo.csv', 'df_q11C_resumo.parquet', 'df_q11D_resumo.csv', 'df_q11D_resumo.parquet', 'df_q11D_volatilidade_alunos.csv', 'df_q11D_volatilidade_alunos.parquet', 'df_q11E_base.csv', 'df_q11E_base.parquet', 'df_q11E_resumo.csv', 'df_q11E_resumo.parquet', 'df_q11F_por_escola.csv', 'df_q11F_por_escola.parquet', 'df_q11F_por_turma.csv', 'df_q11F_por_turma.parquet', 'df_q3_corr.csv', 'df_q3_corr.parquet', 'df_q3_scatter.csv', 'df_q3_scatter.parquet', 'df_q4_quadrantes.csv', 'df_q4_quadrantes.parquet', 'df_q4_scatter.csv', 'df_q4_scatter.parquet', 'df_q5_flags.csv', 'df_q5_flags.parquet', 'df_q5_resumo.csv', 'df_q5_resumo.parquet', 'df_q6_base.csv', 'df_q6_base.parquet', 'df_q6_quadrantes.csv', 'df_q6_quadrantes.parquet', 'df_q7_rank_ipv.csv', 'df_q7_rank_ipv.parquet', 'df_q8_heatmap.csv', 'df_q8_heatmap.parquet', 'df_q9_resumo.csv', 'df_q9_resumo.parquet', 'df_q9_segmentos.csv', 'df_q9_segmentos.parquet']

In [96]:
###############################################################################################################################################
# BLOCO 7.1 - Criar ~/.netrc com o token do Secret "GITHUB_TOKEN" (sem expor o token)
# O que eu faço aqui:
# - Leio o token do Secret do Colab (GITHUB_TOKEN)
# - Se não achar, eu paro com erro claro (pra não gravar "None" no netrc)
# - Gravo ~/.netrc e protejo com permissão 600
###############################################################################################################################################
from google.colab import userdata
import os

token = userdata.get("GITHUB_TOKEN")
user  = "tivanello"

if not token:
    raise ValueError('Secret "GITHUB_TOKEN" não encontrado ou vazio. Confira em Colab > Secrets.')

path = os.path.expanduser("~/.netrc")
with open(path, "w") as f:
    f.write(f"machine github.com\nlogin {user}\npassword {token}\n")
os.chmod(path, 0o600)

print("OK: ~/.netrc criado/atualizado (token não foi exibido).")

OK: ~/.netrc criado/atualizado (token não foi exibido).

In [92]:
###############################################################################################################################################
# BLOCO 7.2 - Teste de acesso ao GitHub (sem expor token)
#
# O que eu faço aqui:
# - Chamo a API do GitHub para confirmar:
#   1) qual usuário o token representa
#   2) se o repo tivanello/fase5 é acessível
###############################################################################################################################################
import json, urllib.request
from google.colab import userdata

token = userdata.get("GITHUB_TOKEN")

def gh_get(url):
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"token {token}")
    req.add_header("Accept", "application/vnd.github+json")
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read().decode("utf-8"))

me = gh_get("https://api.github.com/user")
repo = gh_get("https://api.github.com/repos/tivanello/fase5")

print("Usuário autenticado:", me.get("login"))
print("Repo:", repo.get("full_name"))
print("Permissões:", repo.get("permissions"))

Usuário autenticado: tivanello
Repo: tivanello/fase5
Permissões: {'admin': True, 'maintain': True, 'push': True, 'triage': True, 'pull': True}

In [93]:
%%bash
###############################################################################################################################################
# BLOCO 7.3 — Clonar repo e entrar em /content/fase5
#
# O que eu faço aqui:
# - Vou para /content
# - Clono o repo se ele não existir
# - Entro no diretório do repo e confirmo caminho
###############################################################################################################################################
cd /content || exit 1
if [ ! -d "/content/fase5/.git" ]; then
  rm -rf /content/fase5
  git clone https://github.com/tivanello/fase5.git
fi
cd /content/fase5 || exit 1
pwd
git remote -v

/content/fase5
origin	https://github.com/tivanello/fase5.git (fetch)
origin	https://github.com/tivanello/fase5.git (push)

In [97]:
%%bash
###############################################################################################################################################
# BLOCO 7.4 — CONFIGURAR GIT, COMMITAR E ENVIAR data/processed
#
# O que eu faço aqui:
# - Configuro user.name e user.email no Git
# - Faço commit dos arquivos staged
# - Atualizo a branch local com rebase
# - Envio para o GitHub
###############################################################################################################################################
cd /content/fase5 || exit 1

git config --global user.name "tivanello"
git config --global user.email "tivanello@gmail.com"

git status

git commit -m "Adiciona bases da Pergunta 10 em data/processed"

git pull --rebase origin main

git push origin main

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   data/processed/df_q10_base_final.csv
	new file:   data/processed/df_q10_base_final.parquet
	new file:   data/processed/df_q10_resumo_analise.csv
	new file:   data/processed/df_q10_resumo_analise.parquet
	new file:   data/processed/df_q10_resumo_elegibilidade.csv
	new file:   data/processed/df_q10_resumo_elegibilidade.parquet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/processed/df_q10_pedra_long.csv
	data/processed/df_q10_pedra_long.parquet

[main 4fc612f] Adiciona bases da Pergunta 10 em data/processed
 6 files changed, 1673 insertions(+)
 create mode 100644 data/processed/df_q10_base_final.csv
 create mode 100644 data/processed/df_q10_base_final.parquet
 create mode 100644 data/processed/df_q10_resumo_analise.csv
 create mode 100644 data/processed/df_q10_resumo_analise.parquet
 create mode 100644 data/processed/df_q10_resumo_elegibilidade.csv
 create mode 100644 data/processed/df_q10_resumo_elegibilidade.parquet

From https://github.com/tivanello/fase5
 * branch            main       -> FETCH_HEAD
   733fd17..3962b4a  main       -> origin/main
Successfully rebased and updated refs/heads/main.
To https://github.com/tivanello/fase5.git
   3962b4a..01737fb  main -> main

In [98]:
%%bash
###############################################################################################################################################
# BLOCO — ADICIONAR E ENVIAR A BASE LONGA DA P10
#
# O que eu faço aqui:
# - Adiciono os arquivos df_q10_pedra_long
# - Faço commit
# - Faço push para o GitHub
###############################################################################################################################################
cd /content/fase5 || exit 1

git add data/processed/df_q10_pedra_long.csv data/processed/df_q10_pedra_long.parquet
git status
git commit -m "Adiciona base longa da Pergunta 10 em data/processed"
git pull --rebase origin main
git push origin main

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   data/processed/df_q10_pedra_long.csv
	new file:   data/processed/df_q10_pedra_long.parquet

[main 4ce1f0a] Adiciona base longa da Pergunta 10 em data/processed
 2 files changed, 3677 insertions(+)
 create mode 100644 data/processed/df_q10_pedra_long.csv
 create mode 100644 data/processed/df_q10_pedra_long.parquet
Current branch main is up to date.

From https://github.com/tivanello/fase5
 * branch            main       -> FETCH_HEAD
To https://github.com/tivanello/fase5.git
   01737fb..4ce1f0a  main -> main