<a href="https://colab.research.google.com/github/tivanello/fase5/blob/main/notebooks/fase5_pergunta10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ============================================================
# BLOCO 1 —IMPORTAR O DATAFRAME do Git
# Objetivo:
# - Clonar o repositório no Colab
# - Localizar o arquivo tratado
# - Carregar o arquivo df_fase5.csv em um DataFrame
# ============================================================

import os
import pandas as pd

REPO_DIR = "/content/fase5"
ARQUIVO = f"{REPO_DIR}/data/processed/df_fase5.csv"

# Clonar o repositório apenas se ainda não existir
if not os.path.exists(REPO_DIR):
    !git clone https://github.com/tivanello/fase5.git {REPO_DIR}
else:
    print("Repositório já existe no ambiente.")

# Carregar o arquivo
df_fase5_p10 = pd.read_csv(ARQUIVO)

# Conferência inicial
print("Dimensão do dataframe:", df_fase5_p10.shape)
display(df_fase5_p10.head())

Cloning into '/content/fase5'...
remote: Enumerating objects: 296, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 296 (delta 9), reused 10 (delta 4), pack-reused 274 (from 2)
Receiving objects: 100% (296/296), 94.15 MiB | 44.59 MiB/s, done.
Resolving deltas: 100% (115/115), done.
Dimensão do dataframe: (3030, 72)

,RA,Fase,Turma,Ano nasc,Idade 22,Gênero,Ano ingresso,Instituição de ensino,Pedra 20,Pedra 21,...,Avaliador6_id,FaseIdeal_txt,Fase_num,Fase_sufixo,FaseIdeal_num,ra_num,INDE_final,INDE_fonte,PEDRA_final,PEDRA_fonte
0,RA-1,7,A,2003.0,19.0,Menina,2016,Escola Pública,Ametista,Ametista,...,NaN,Fase 8 (Universitários),7.0,NaN,8,1,5.783,INDE 2022,Quartzo,Pedra 2022
1,RA-2,7,A,2005.0,17.0,Menina,2017,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,2,7.055,INDE 2022,Ametista,Pedra 2022
2,RA-3,7,A,2005.0,17.0,Menina,2016,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,3,6.591,INDE 2022,Ágata,Pedra 2022
3,RA-4,7,A,2005.0,17.0,Menino,2017,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,4,5.951,INDE 2022,Quartzo,Pedra 2022
4,RA-5,7,A,2005.0,17.0,Menina,2016,Rede Decisão,Ametista,Ametista,...,NaN,Fase 7 (3º EM),7.0,NaN,7,5,7.427,INDE 2022,Ametista,Pedra 2022

In [3]:
df_fase5_p10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 72 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     3030 non-null   object
 1   Fase                   3030 non-null   object
 2   Turma                  3030 non-null   object
 3   Ano nasc               860 non-null    float64
 4   Idade 22               860 non-null    float64
 5   Gênero                 3030 non-null   object
 6   Ano ingresso           3030 non-null   int64
 7   Instituição de ensino  3029 non-null   object
 8   Pedra 20               754 non-null    object
 9   Pedra 21               1061 non-null   object
 10  Pedra 22               1932 non-null   object
 11  INDE 22                1932 non-null   float64
 12  Cg                     860 non-null    float64
 13  Cf                     860 non-null    float64
 14  Ct                     860 non-null    float64
 15  Nº Av                  2954 non-null   float64
 16  Avaliador1             2827 non-null   object
 17  Rec Av1                860 non-null    object
 18  Avaliador2             2827 non-null   object
 19  Rec Av2                860 non-null    object
 20  Avaliador3             2034 non-null   object
 21  Rec Av3                860 non-null    object
 22  Avaliador4             1051 non-null   object
 23  Rec Av4                296 non-null    object
 24  IAA                    2865 non-null   float64
 25  IEG                    2954 non-null   float64
 26  IPS                    2859 non-null   float64
 27  Rec Psicologia         860 non-null    object
 28  IDA                    2852 non-null   float64
 29  Matem                  858 non-null    float64
 30  Portug                 858 non-null    float64
 31  Inglês                 283 non-null    float64
 32  Indicado               860 non-null    object
 33  Atingiu PV             860 non-null    object
 34  IPV                    2852 non-null   float64
 35  IAN                    3030 non-null   float64
 36  Destaque IEG           860 non-null    object
 37  Destaque IDA           860 non-null    object
 38  Destaque IPV           860 non-null    object
 39  ano_base               3030 non-null   int64
 40  INDE 2023              931 non-null    float64
 41  Pedra 2023             931 non-null    object
 42  Data de Nasc           2170 non-null   object
 43  Idade                  2170 non-null   float64
 44  Pedra 23               690 non-null    object
 45  INDE 23                690 non-null    float64
 46  IPP                    1992 non-null   float64
 47  Mat                    1988 non-null   float64
 48  Por                    1987 non-null   float64
 49  Ing                    808 non-null    float64
 50  INDE 2024              1054 non-null   float64
 51  Pedra 2024             1092 non-null   object
 52  Avaliador5             148 non-null    object
 53  Avaliador6             6 non-null      object
 54  Escola                 1155 non-null   object
 55  Ativo/ Inativo         1156 non-null   object
 56  Defasagem_final        3030 non-null   int64
 57  Avaliador1_id          2827 non-null   float64
 58  Avaliador2_id          2827 non-null   float64
 59  Avaliador3_id          2034 non-null   float64
 60  Avaliador4_id          1051 non-null   float64
 61  Avaliador5_id          148 non-null    float64
 62  Avaliador6_id          6 non-null      float64
 63  FaseIdeal_txt          3030 non-null   object
 64  Fase_num               2603 non-null   float64
 65  Fase_sufixo            922 non-null    object
 66  FaseIdeal_num          3030 non-null   int64
 67  ra_num                 3030 non-null   int64
 68  INDE_final             2845 non-null   float64
 69  INDE_fonte             2845 non-null   object
 70  PEDRA_final            2883 non-null   object
 71  PEDRA_fonte            2883 non-null   object
dtypes: float64(32), int64(5), object(35)
memory usage: 1.7+ MB

In [4]:
# ============================================================
# BLOCO — LISTAR TODAS AS COLUNAS RELACIONADAS A "FASE"
# Objetivo:
# - Encontrar no df_fase5 todas as colunas cujo nome contenha "fase"
# - Ignorar maiúsculas e minúsculas
# ============================================================

colunas_fase = [col for col in df_fase5_p10.columns if "fase" in col.lower()]

print("Colunas relacionadas a 'fase':")
for col in colunas_fase:
    print("-", col)

print("\nTotal encontrado:", len(colunas_fase))

Colunas relacionadas a 'fase':
- Fase
- FaseIdeal_txt
- Fase_num
- Fase_sufixo
- FaseIdeal_num

Total encontrado: 5

In [5]:
# ============================================================
# BLOCO — INSPECIONAR CAMPOS DE FASE
# Objetivo:
# - Ver todos os valores distintos das colunas ligadas à fase
# - Ver como elas se combinam entre si
# ============================================================

df_base = df_fase5_p10.copy()

colunas_fase = [
    "Fase",
    "FaseIdeal_txt",
    "Fase_num",
    "Fase_sufixo",
    "FaseIdeal_num"
]

print("============================================================")
print("VALORES DISTINTOS POR COLUNA")
print("============================================================")

for col in colunas_fase:
    print(f"\nColuna: {col}")
    print(f"Quantidade de valores distintos: {df_base[col].nunique(dropna=False)}")
    valores = df_base[col].drop_duplicates().tolist()
    print(valores)

print("\n============================================================")
print("COMBINAÇÕES ÚNICAS ENTRE AS COLUNAS")
print("============================================================")

df_combinacoes_fase = (
    df_base[colunas_fase]
    .drop_duplicates()
    .sort_values(["Fase_num", "Fase", "Fase_sufixo", "FaseIdeal_num", "FaseIdeal_txt"], na_position="last")
    .reset_index(drop=True)
)

display(df_combinacoes_fase)

print("\n============================================================")
print("CONTAGEM POR COMBINAÇÃO")
print("============================================================")

df_contagem_fase = (
    df_base
    .groupby(colunas_fase, dropna=False)
    .size()
    .reset_index(name="qtd")
    .sort_values(["Fase_num", "Fase", "Fase_sufixo", "FaseIdeal_num", "FaseIdeal_txt"], na_position="last")
    .reset_index(drop=True)
)

display(df_contagem_fase)

============================================================
VALORES DISTINTOS POR COLUNA
============================================================

Coluna: Fase
Quantidade de valores distintos: 88
['7', '6', '5', '4', '3', '2', '1', '0', 'ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', 'FASE 8', '1A', '1B', '1C', '1D', '1E', '1G', '1H', '1J', '1K', '1L', '1M', '1N', '1P', '1R', '2A', '2B', '2C', '2D', '2G', '2H', '2I', '2K', '2L', '2M', '2N', '2P', '2R', '2U', '3A', '3B', '3C', '3D', '3F', '3G', '3H', '3I', '3K', '3L', '3M', '3N', '3P', '3R', '3U', '4A', '4B', '4C', '4F', '4H', '4L', '4M', '4N', '4R', '5A', '5B', '5C', '5D', '5F', '5G', '5L', '5M', '5N', '6A', '6L', '7A', '7E', '8A', '8B', '8D', '8E', '8F', '9']

Coluna: FaseIdeal_txt
Quantidade de valores distintos: 11
['Fase 8 (Universitários)', 'Fase 7 (3º EM)', 'Fase 6 (2º EM)', 'Fase 5 (1º EM)', 'Fase 3 (7º e 8º ano)', 'Fase 4 (9º ano)', 'Fase 2 (5º e 6º ano)', 'Fase 1 (4º ano)', 'ALFA (2º e 3º ano)', 'ALFA (1º e 2º ano)', 'Fase 1 (3º e 4º ano)']

Coluna: Fase_num
Quantidade de valores distintos: 11
[7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.0, nan, 8.0, 9.0]

Coluna: Fase_sufixo
Quantidade de valores distintos: 18
[nan, 'a', 'b', 'c', 'd', 'e', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 'i', 'u', 'f']

Coluna: FaseIdeal_num
Quantidade de valores distintos: 8
[8, 7, 6, 5, 3, 4, 2, 1]

============================================================
COMBINAÇÕES ÚNICAS ENTRE AS COLUNAS
============================================================

     Fase            FaseIdeal_txt  Fase_num Fase_sufixo  FaseIdeal_num
0       0          Fase 1 (4º ano)       0.0         NaN              1
1       0       ALFA (2º e 3º ano)       0.0         NaN              2
2       0     Fase 2 (5º e 6º ano)       0.0         NaN              2
3       0     Fase 3 (7º e 8º ano)       0.0         NaN              3
4       1          Fase 1 (4º ano)       1.0         NaN              1
..    ...                      ...       ...         ...            ...
271     9  Fase 8 (Universitários)       9.0         NaN              8
272  ALFA       ALFA (1º e 2º ano)       NaN         NaN              1
273  ALFA     Fase 1 (3º e 4º ano)       NaN         NaN              1
274  ALFA     Fase 2 (5º e 6º ano)       NaN         NaN              2
275  ALFA     Fase 3 (7º e 8º ano)       NaN         NaN              3

[276 rows x 5 columns]

============================================================
CONTAGEM POR COMBINAÇÃO
============================================================

     Fase            FaseIdeal_txt  Fase_num Fase_sufixo  FaseIdeal_num  qtd
0       0          Fase 1 (4º ano)       0.0         NaN              1   68
1       0       ALFA (2º e 3º ano)       0.0         NaN              2   69
2       0     Fase 2 (5º e 6º ano)       0.0         NaN              2   52
3       0     Fase 3 (7º e 8º ano)       0.0         NaN              3    1
4       1          Fase 1 (4º ano)       1.0         NaN              1   28
..    ...                      ...       ...         ...            ...  ...
271     9  Fase 8 (Universitários)       9.0         NaN              8   38
272  ALFA       ALFA (1º e 2º ano)       NaN         NaN              1  163
273  ALFA     Fase 1 (3º e 4º ano)       NaN         NaN              1  192
274  ALFA     Fase 2 (5º e 6º ano)       NaN         NaN              2   71
275  ALFA     Fase 3 (7º e 8º ano)       NaN         NaN              3    1

[276 rows x 6 columns]

In [6]:
# ============================================================
# BLOCO 1 — TRATAR ALFA COMO FASE 0
# Objetivo:
# - Padronizar a coluna Fase_num
# - Considerar ALFA como fase 0
# ============================================================

import pandas as pd
import numpy as np

df_fase5_p10 = df_fase5_p10.copy()

df_fase5_p10["Fase_num"] = pd.to_numeric(df_fase5_p10["Fase_num"], errors="coerce")
df_fase5_p10["FaseIdeal_num"] = pd.to_numeric(df_fase5_p10["FaseIdeal_num"], errors="coerce")

mask_alfa = df_fase5_p10["Fase"].astype(str).str.strip().str.upper().eq("ALFA")

total_alfa = mask_alfa.sum()
nulos_antes = df_fase5.loc[mask_alfa, "Fase_num"].isna().sum()

df_fase5_p10.loc[mask_alfa, "Fase_num"] = 0

print("AJUSTE ALFA -> 0")
print("Total de registros com Fase = ALFA:", total_alfa)
print("Registros ALFA com Fase_num nulo antes do ajuste:", nulos_antes)

print("\nValores únicos de Fase_num após o ajuste:")
print(sorted(df_fase5_p10["Fase_num"].dropna().unique()))

NameError: name 'df_fase5' is not defined

In [7]:
# ============================================================
# BLOCO 2 — COMPARAR Fase_num COM FaseIdeal_num
# Objetivo:
# - Ver nulos
# - Ver distribuição
# - Ver cruzamento entre fase atual e fase ideal
# ============================================================

print("Nulos por coluna:")
print(df_fase5_p10[["Fase_num", "FaseIdeal_num"]].isna().sum())

print("\nValores únicos de Fase_num:")
print(sorted(df_fase5_p10["Fase_num"].dropna().unique()))

print("\nValores únicos de FaseIdeal_num:")
print(sorted(df_fase5_p10["FaseIdeal_num"].dropna().unique()))

print("\nCruzamento Fase_num x FaseIdeal_num:")
tabela_cruzada = pd.crosstab(
    df_fase5_p10["Fase_num"],
    df_fase5_p10["FaseIdeal_num"],
    dropna=False
)

display(tabela_cruzada)

print("\nAmostra para conferência:")
display(
    df_fase5_p10[
        ["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]
    ].head(20)
)

Nulos por coluna:
Fase_num         427
FaseIdeal_num      0
dtype: int64

Valores únicos de Fase_num:
[np.float64(0.0), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]

Valores únicos de FaseIdeal_num:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

Cruzamento Fase_num x FaseIdeal_num:

FaseIdeal_num    1    2    3    4   5   6   7    8
Fase_num
0.0             68  121    1    0   0   0   0    0
1.0            123  354   69    4   0   0   0    0
2.0              5  231  274   27   2   1   0    0
3.0              0   38  253  130  52  15   2    1
4.0              0    1   41   84  99  47  11    2
5.0              0    0    5   26  53  78  58    5
6.0              0    0    0    0   0  25  44    7
7.0              0    0    0    0  18  11  30   22
8.0              0    0    0    0   0   0   2  125
9.0              0    0    0    0   0   0   0   38
NaN            355   71    1    0   0   0   0    0

Amostra para conferência:

       RA  ano_base Fase  Fase_num            FaseIdeal_txt  FaseIdeal_num
0    RA-1      2022    7       7.0  Fase 8 (Universitários)              8
1    RA-2      2022    7       7.0           Fase 7 (3º EM)              7
2    RA-3      2022    7       7.0           Fase 7 (3º EM)              7
3    RA-4      2022    7       7.0           Fase 7 (3º EM)              7
4    RA-5      2022    7       7.0           Fase 7 (3º EM)              7
5    RA-6      2022    7       7.0  Fase 8 (Universitários)              8
6    RA-7      2022    7       7.0  Fase 8 (Universitários)              8
7    RA-8      2022    7       7.0  Fase 8 (Universitários)              8
8    RA-9      2022    7       7.0  Fase 8 (Universitários)              8
9   RA-10      2022    7       7.0  Fase 8 (Universitários)              8
10  RA-11      2022    7       7.0  Fase 8 (Universitários)              8
11  RA-12      2022    7       7.0           Fase 7 (3º EM)              7
12  RA-13      2022    7       7.0  Fase 8 (Universitários)              8
13  RA-14      2022    7       7.0  Fase 8 (Universitários)              8
14  RA-15      2022    7       7.0  Fase 8 (Universitários)              8
15  RA-16      2022    7       7.0  Fase 8 (Universitários)              8
16  RA-17      2022    7       7.0  Fase 8 (Universitários)              8
17  RA-18      2022    7       7.0  Fase 8 (Universitários)              8
18  RA-19      2022    7       7.0  Fase 8 (Universitários)              8
19  RA-20      2022    7       7.0  Fase 8 (Universitários)              8

In [8]:
# ============================================================
# BLOCO — PADRONIZAR COLUNA Fase COMO "FASE X"
# Objetivo:
# - Acrescentar a expressão "FASE " antes do número da fase
# - Manter apenas o número da própria coluna Fase
# ============================================================

df_fase5_p10["Fase"] = (
    pd.to_numeric(df_fase5_p10["Fase"], errors="coerce")
    .astype("Int64")
    .astype("string")
    .radd("FASE ")
)

print("Amostra para conferência:")
display(df_fase5_p10[["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]].head(20))

Amostra para conferência:

       RA  ano_base    Fase  Fase_num            FaseIdeal_txt  FaseIdeal_num
0    RA-1      2022  FASE 7       7.0  Fase 8 (Universitários)              8
1    RA-2      2022  FASE 7       7.0           Fase 7 (3º EM)              7
2    RA-3      2022  FASE 7       7.0           Fase 7 (3º EM)              7
3    RA-4      2022  FASE 7       7.0           Fase 7 (3º EM)              7
4    RA-5      2022  FASE 7       7.0           Fase 7 (3º EM)              7
5    RA-6      2022  FASE 7       7.0  Fase 8 (Universitários)              8
6    RA-7      2022  FASE 7       7.0  Fase 8 (Universitários)              8
7    RA-8      2022  FASE 7       7.0  Fase 8 (Universitários)              8
8    RA-9      2022  FASE 7       7.0  Fase 8 (Universitários)              8
9   RA-10      2022  FASE 7       7.0  Fase 8 (Universitários)              8
10  RA-11      2022  FASE 7       7.0  Fase 8 (Universitários)              8
11  RA-12      2022  FASE 7       7.0           Fase 7 (3º EM)              7
12  RA-13      2022  FASE 7       7.0  Fase 8 (Universitários)              8
13  RA-14      2022  FASE 7       7.0  Fase 8 (Universitários)              8
14  RA-15      2022  FASE 7       7.0  Fase 8 (Universitários)              8
15  RA-16      2022  FASE 7       7.0  Fase 8 (Universitários)              8
16  RA-17      2022  FASE 7       7.0  Fase 8 (Universitários)              8
17  RA-18      2022  FASE 7       7.0  Fase 8 (Universitários)              8
18  RA-19      2022  FASE 7       7.0  Fase 8 (Universitários)              8
19  RA-20      2022  FASE 7       7.0  Fase 8 (Universitários)              8

In [9]:
# ============================================================
# BLOCO 1 — CONFERIR MAPEAMENTO DAS FASES DA P10
# Objetivo:
# - Identificar quais valores de Fase_num correspondem
#   a Quartzo, Ágata, Ametista e Topázio
# ============================================================

df_mapa_fases = (
    df_fase5_p10[["Fase", "Fase_num", "PEDRA_final", "PEDRA_fonte"]]
    .drop_duplicates()
    .sort_values(["Fase_num", "Fase"])
    .reset_index(drop=True)
)

print("Mapa de fases para conferência:")
display(df_mapa_fases)

Mapa de fases para conferência:

      Fase  Fase_num PEDRA_final PEDRA_fonte
0   FASE 0       0.0    Ametista  Pedra 2022
1   FASE 0       0.0     Topázio  Pedra 2022
2   FASE 0       0.0       Ágata  Pedra 2022
3   FASE 0       0.0     Quartzo  Pedra 2022
4   FASE 1       1.0     Topázio  Pedra 2022
..     ...       ...         ...         ...
92    <NA>       NaN       Agata  Pedra 2023
93    <NA>       NaN    Ametista  Pedra 2024
94    <NA>       NaN     Topázio  Pedra 2024
95    <NA>       NaN     Quartzo  Pedra 2024
96    <NA>       NaN       Agata  Pedra 2024

[97 rows x 4 columns]

In [10]:
# ============================================================
# BLOCO — CONTAR NULOS NA COLUNA Fase
# Objetivo:
# - Mostrar quantos registros da coluna Fase estão nulos
# ============================================================

qtd_nulos_fase = df_fase5_p10["Fase"].isna().sum()

print("Quantidade de nulos na coluna Fase:")
print(qtd_nulos_fase)

Quantidade de nulos na coluna Fase:
2132

In [11]:
# ============================================================
# BLOCO — VERIFICAR Fase_num NAS LINHAS EM QUE Fase ESTÁ NULA
# Objetivo:
# - Filtrar os registros onde Fase está nula
# - Verificar se nessas linhas existe valor em Fase_num
# ============================================================

df_fase_nula = df_fase5_p10[df_fase5_p10["Fase"].isna()].copy()

print("Quantidade de linhas com Fase nula:")
print(len(df_fase_nula))

print("\nQuantidade de linhas com Fase nula e Fase_num preenchida:")
print(df_fase_nula["Fase_num"].notna().sum())

print("\nQuantidade de linhas com Fase nula e Fase_num também nula:")
print(df_fase_nula["Fase_num"].isna().sum())

print("\nValores únicos de Fase_num nas linhas com Fase nula:")
print(sorted(df_fase_nula["Fase_num"].dropna().unique()))

print("\nAmostra para conferência:")
display(df_fase_nula[["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]].head(20))

Quantidade de linhas com Fase nula:
2132

Quantidade de linhas com Fase nula e Fase_num preenchida:
1705

Quantidade de linhas com Fase nula e Fase_num também nula:
427

Valores únicos de Fase_num nas linhas com Fase nula:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0)]

Amostra para conferência:

         RA  ano_base  Fase  Fase_num         FaseIdeal_txt  FaseIdeal_num
860  RA-861      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
861  RA-862      2023  <NA>       NaN  Fase 1 (3º e 4º ano)              1
862  RA-863      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
863  RA-864      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
864  RA-865      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
865  RA-866      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
866  RA-867      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
867  RA-868      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
868  RA-869      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
869  RA-870      2023  <NA>       NaN  Fase 1 (3º e 4º ano)              1
870  RA-871      2023  <NA>       NaN  Fase 1 (3º e 4º ano)              1
871  RA-872      2023  <NA>       NaN  Fase 2 (5º e 6º ano)              2
872  RA-873      2023  <NA>       NaN  Fase 2 (5º e 6º ano)              2
873  RA-874      2023  <NA>       NaN  Fase 1 (3º e 4º ano)              1
874  RA-875      2023  <NA>       NaN  Fase 1 (3º e 4º ano)              1
875  RA-876      2023  <NA>       NaN    ALFA (1º e 2º ano)              1
876  RA-877      2023  <NA>       NaN  Fase 1 (3º e 4º ano)              1
877  RA-878      2023  <NA>       NaN  Fase 2 (5º e 6º ano)              2
878  RA-879      2023  <NA>       NaN  Fase 1 (3º e 4º ano)              1
879  RA-880      2023  <NA>       NaN    ALFA (1º e 2º ano)              1

In [12]:
# ============================================================
# BLOCO — PREENCHER Fase NULA COM BASE EM Fase_num
# Objetivo:
# - Identificar linhas em que Fase está nula
# - Preencher com "FASE X", onde X vem de Fase_num
# ============================================================

df_fase5_p10 = df_fase5_p10.copy()

mask_fase_nula = df_fase5_p10["Fase"].isna() & df_fase5_p10["Fase_num"].notna()

df_fase5_p10.loc[mask_fase_nula, "Fase"] = (
    "FASE " +
    df_fase5_p10.loc[mask_fase_nula, "Fase_num"]
    .astype("Int64")
    .astype("string")
)

print("Quantidade de linhas preenchidas em Fase:")
print(mask_fase_nula.sum())

print("\nAmostra para conferência:")
display(
    df_fase5_p10.loc[
        mask_fase_nula,
        ["RA", "ano_base", "Fase", "Fase_num", "FaseIdeal_txt", "FaseIdeal_num"]
    ].head(20)
)

Quantidade de linhas preenchidas em Fase:
1705

Amostra para conferência:

           RA  ano_base    Fase  Fase_num         FaseIdeal_txt  FaseIdeal_num
1091  RA-1015      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1092   RA-734      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1093   RA-687      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1094  RA-1016      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1095  RA-1017      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1096   RA-688      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1097  RA-1018      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1
1098   RA-696      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1
1099  RA-1019      2023  FASE 1       1.0    ALFA (1º e 2º ano)              1
1100   RA-514      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1101  RA-1020      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1
1102  RA-1021      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1
1103  RA-1022      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1
1104  RA-1023      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1
1105   RA-699      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1106   RA-480      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1107   RA-678      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1108  RA-1024      2023  FASE 1       1.0  Fase 2 (5º e 6º ano)              2
1109   RA-502      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1
1110  RA-1025      2023  FASE 1       1.0  Fase 1 (3º e 4º ano)              1

In [13]:
# ============================================================
# BLOCO — MOSTRAR VALORES ORDENADOS DA COLUNA Fase
# Objetivo:
# - Exibir os valores distintos da coluna Fase em ordem
# ============================================================

valores_fase = sorted(df_fase5_p10["Fase"].dropna().astype(str).unique())

valores_fase_num = sorted(df_fase5_p10["Fase_num"].dropna().astype(str).unique())

valores_FaseIdeal_txt = sorted(df_fase5_p10["FaseIdeal_txt"].dropna().astype(str).unique())

valores_FaseIdeal_num = sorted(df_fase5_p10["FaseIdeal_num"].dropna().astype(str).unique())

print("Valores distintos da coluna Fase:")
print(valores_fase)

print("Valores distintos da coluna Fase_num:")
print(valores_fase_num)

print("Valores distintos da coluna FaseIdeal_txt:")
print(valores_FaseIdeal_txt)

print("Valores distintos da coluna FaseIdeal_num:")
print(valores_FaseIdeal_num)

Valores distintos da coluna Fase:
['FASE 0', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', 'FASE 8', 'FASE 9']
Valores distintos da coluna Fase_num:
['0.0', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0']
Valores distintos da coluna FaseIdeal_txt:
['ALFA (1º e 2º ano)', 'ALFA (2º e 3º ano)', 'Fase 1 (3º e 4º ano)', 'Fase 1 (4º ano)', 'Fase 2 (5º e 6º ano)', 'Fase 3 (7º e 8º ano)', 'Fase 4 (9º ano)', 'Fase 5 (1º EM)', 'Fase 6 (2º EM)', 'Fase 7 (3º EM)', 'Fase 8 (Universitários)']
Valores distintos da coluna FaseIdeal_num:
['1', '2', '3', '4', '5', '6', '7', '8']

In [14]:
# ============================================================
# BLOCO — PADRONIZAR FaseIdeal_txt
# Objetivo:
# - Unificar categorias equivalentes em FaseIdeal_txt
# ============================================================

df_fase5_p10 = df_fase5_p10.copy()

mapa_faseideal_txt = {
    "ALFA (2º e 3º ano)": "ALFA (1º e 2º ano)",
    "Fase 1 (4º ano)": "Fase 1 (3º e 4º ano)"
}

df_fase5_p10["FaseIdeal_txt"] = df_fase5_p10["FaseIdeal_txt"].replace(mapa_faseideal_txt)

print("Valores únicos atualizados de FaseIdeal_txt:")
print(sorted(df_fase5_p10["FaseIdeal_txt"].dropna().unique()))

print("\nContagem por FaseIdeal_txt:")
print(df_fase5_p10["FaseIdeal_txt"].value_counts(dropna=False).sort_index())

Valores únicos atualizados de FaseIdeal_txt:
['ALFA (1º e 2º ano)', 'Fase 1 (3º e 4º ano)', 'Fase 2 (5º e 6º ano)', 'Fase 3 (7º e 8º ano)', 'Fase 4 (9º ano)', 'Fase 5 (1º EM)', 'Fase 6 (2º EM)', 'Fase 7 (3º EM)', 'Fase 8 (Universitários)']

Contagem por FaseIdeal_txt:
FaseIdeal_txt
ALFA (1º e 2º ano)         236
Fase 1 (3º e 4º ano)       386
Fase 2 (5º e 6º ano)       745
Fase 3 (7º e 8º ano)       644
Fase 4 (9º ano)            271
Fase 5 (1º EM)             224
Fase 6 (2º EM)             177
Fase 7 (3º EM)             147
Fase 8 (Universitários)    200
Name: count, dtype: int64

In [15]:
# ============================================================
# BLOCO — VERIFICAR NULOS EM FaseIdeal_txt E FaseIdeal_num
# Objetivo:
# - Mostrar a quantidade de nulos nas colunas
#   FaseIdeal_txt e FaseIdeal_num
# ============================================================

print("Quantidade de nulos em FaseIdeal_txt:")
print(df_fase5_p10["FaseIdeal_txt"].isna().sum())

print("\nQuantidade de nulos em FaseIdeal_num:")
print(df_fase5_p10["FaseIdeal_num"].isna().sum())

Quantidade de nulos em FaseIdeal_txt:
0

Quantidade de nulos em FaseIdeal_num:
0

In [16]:
# ============================================================
# BLOCO — VERIFICAR NULOS NAS COLUNAS DA P10
# Objetivo:
# - Mostrar a quantidade e o percentual de nulos
#   nas colunas selecionadas para a Pergunta 10
# ============================================================

colunas_p10 = [
    "RA",
    "ra_num",
    "ano_base",
    "Fase",
    "Fase_num",
    "FaseIdeal_txt",
    "FaseIdeal_num",
    "PEDRA_final",
    "PEDRA_fonte",
    "INDE_final",
    "IDA",
    "IEG",
    "IPV",
    "IAN",
    "IPP",
    "Defasagem_final"
]

resumo_nulos_p10 = pd.DataFrame({
    "coluna": colunas_p10,
    "qtd_nulos": [df_fase5_p10[col].isna().sum() for col in colunas_p10],
    "percentual_nulos": [round(df_fase5_p10[col].isna().mean() * 100, 2) for col in colunas_p10]
})

print("Resumo de nulos nas colunas da P10:")
display(resumo_nulos_p10)

Resumo de nulos nas colunas da P10:

             coluna  qtd_nulos  percentual_nulos
0                RA          0              0.00
1            ra_num          0              0.00
2          ano_base          0              0.00
3              Fase        427             14.09
4          Fase_num        427             14.09
5     FaseIdeal_txt          0              0.00
6     FaseIdeal_num          0              0.00
7       PEDRA_final        147              4.85
8       PEDRA_fonte        147              4.85
9        INDE_final        185              6.11
10              IDA        178              5.87
11              IEG         76              2.51
12              IPV        178              5.87
13              IAN          0              0.00
14              IPP       1038             34.26
15  Defasagem_final          0              0.00

In [17]:
# ============================================================
# BLOCO 1 — BASE DA PERGUNTA 10
# Objetivo:
# - Selecionar apenas as colunas necessárias
# - Verificar valores nulos nas colunas principais
# ============================================================

import pandas as pd

colunas_p10 = [
    "RA",
    "ra_num",
    "ano_base",
    "Fase",
    "Fase_num",
    "FaseIdeal_txt",
    "FaseIdeal_num",
    "PEDRA_final",
    "PEDRA_fonte",
    "INDE_final",
    "IDA",
    "IEG",
    "IPV",
    "IAN",
    "IPP",
    "Defasagem_final"
]

df_p10 = df_fase5_p10[colunas_p10].copy()

print("Dimensão da base P10:", df_p10.shape)

print("\nNulos por coluna:")
print(df_p10.isna().sum())

print("\nAmostra:")
display(df_p10.head())

Dimensão da base P10: (3030, 16)

Nulos por coluna:
RA                    0
ra_num                0
ano_base              0
Fase                427
Fase_num            427
FaseIdeal_txt         0
FaseIdeal_num         0
PEDRA_final         147
PEDRA_fonte         147
INDE_final          185
IDA                 178
IEG                  76
IPV                 178
IAN                   0
IPP                1038
Defasagem_final       0
dtype: int64

Amostra:

,RA,ra_num,ano_base,Fase,Fase_num,FaseIdeal_txt,FaseIdeal_num,PEDRA_final,PEDRA_fonte,INDE_final,IDA,IEG,IPV,IAN,IPP,Defasagem_final
0,RA-1,1,2022,FASE 7,7.0,Fase 8 (Universitários),8,Quartzo,Pedra 2022,5.783,4.0,4.1,7.278,5.0,NaN,-1
1,RA-2,2,2022,FASE 7,7.0,Fase 7 (3º EM),7,Ametista,Pedra 2022,7.055,6.8,5.2,6.778,10.0,NaN,0
2,RA-3,3,2022,FASE 7,7.0,Fase 7 (3º EM),7,Ágata,Pedra 2022,6.591,5.6,7.9,7.556,10.0,NaN,0
3,RA-4,4,2022,FASE 7,7.0,Fase 7 (3º EM),7,Quartzo,Pedra 2022,5.951,5.0,4.5,5.278,10.0,NaN,0
4,RA-5,5,2022,FASE 7,7.0,Fase 7 (3º EM),7,Ametista,Pedra 2022,7.427,5.2,8.6,7.389,10.0,NaN,0

In [18]:
# ============================================================
# BLOCO — CHECAGEM FINAL DA BASE P10
# Objetivo:
# - Verificar dimensão, nulos e distribuição das principais colunas
# ============================================================

print("Dimensão do df_p10:", df_p10.shape)

print("\nNulos por coluna:")
print(df_p10.isna().sum())

print("\nValores únicos de Fase:")
print(sorted(df_p10["Fase"].dropna().unique()))

print("\nValores únicos de PEDRA_final:")
print(sorted(df_p10["PEDRA_final"].dropna().unique()))

print("\nDistribuição por ano_base:")
print(df_p10["ano_base"].value_counts().sort_index())

print("\nDistribuição por Fase:")
print(df_p10["Fase"].value_counts().sort_index())

print("\nDistribuição por PEDRA_final:")
print(df_p10["PEDRA_final"].value_counts(dropna=False).sort_index())

Dimensão do df_p10: (3030, 16)

Nulos por coluna:
RA                    0
ra_num                0
ano_base              0
Fase                427
Fase_num            427
FaseIdeal_txt         0
FaseIdeal_num         0
PEDRA_final         147
PEDRA_fonte         147
INDE_final          185
IDA                 178
IEG                  76
IPV                 178
IAN                   0
IPP                1038
Defasagem_final       0
dtype: int64

Valores únicos de Fase:
['FASE 0', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', 'FASE 8', 'FASE 9']

Valores únicos de PEDRA_final:
['Agata', 'Ametista', 'INCLUIR', 'Quartzo', 'Topázio', 'Ágata']

Distribuição por ano_base:
ano_base
2022     860
2023    1014
2024    1156
Name: count, dtype: int64

Distribuição por Fase:
Fase
FASE 0    190
FASE 1    550
FASE 2    540
FASE 3    491
FASE 4    285
FASE 5    225
FASE 6     76
FASE 7     81
FASE 8    127
FASE 9     38
Name: count, dtype: Int64

Distribuição por PEDRA_final:
PEDRA_final
Agata        471
Ametista    1120
INCLUIR       38
Quartzo      316
Topázio      688
Ágata        250
NaN          147
Name: count, dtype: int64

In [19]:
# ============================================================
# BLOCO — CONTAGEM DA COLUNA PEDRA_final
# Objetivo:
# - Mostrar a quantidade de registros por valor de PEDRA_final
# - Incluir valores nulos na contagem
# ============================================================

print("Contagem de registros por PEDRA_final:")
print(df_p10["PEDRA_final"].value_counts(dropna=False))

Contagem de registros por PEDRA_final:
PEDRA_final
Ametista    1120
Topázio      688
Agata        471
Quartzo      316
Ágata        250
NaN          147
INCLUIR       38
Name: count, dtype: int64

In [20]:
# ============================================================
# BLOCO P10.3 — CONSULTA DAS COLUNAS RELACIONADAS A PEDRA
# Objetivo:
# - localizar todas as colunas com "PEDRA" no nome
# - exibir essas colunas em uma amostra da base
# ============================================================

colunas_pedra = [c for c in df_fase5_p10.columns if "PEDRA" in c.upper()]

print("Quantidade de colunas com referência a PEDRA:", len(colunas_pedra))
print("\nColunas encontradas:")
for c in colunas_pedra:
    print("-", c)

print("\nAmostra das colunas de PEDRA:")
display(df_fase5_p10[colunas_pedra].head(10))

Quantidade de colunas com referência a PEDRA: 8

Colunas encontradas:
- Pedra 20
- Pedra 21
- Pedra 22
- Pedra 2023
- Pedra 23
- Pedra 2024
- PEDRA_final
- PEDRA_fonte

Amostra das colunas de PEDRA:

,Pedra 20,Pedra 21,Pedra 22,Pedra 2023,Pedra 23,Pedra 2024,PEDRA_final,PEDRA_fonte
0,Ametista,Ametista,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
1,Ametista,Ametista,Ametista,NaN,NaN,NaN,Ametista,Pedra 2022
2,Ametista,Ametista,Ágata,NaN,NaN,NaN,Ágata,Pedra 2022
3,Ametista,Ametista,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
4,Ametista,Ametista,Ametista,NaN,NaN,NaN,Ametista,Pedra 2022
5,NaN,Ágata,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
6,Ametista,Ametista,Ágata,NaN,NaN,NaN,Ágata,Pedra 2022
7,Quartzo,Ágata,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022
8,Ametista,Ametista,Topázio,NaN,NaN,NaN,Topázio,Pedra 2022
9,NaN,Ágata,Quartzo,NaN,NaN,NaN,Quartzo,Pedra 2022

In [21]:
# ============================================================
# BLOCO P10.15 — VALIDAR PEDRA 23 x PEDRA 2023 POR RA
# Objetivo:
# - consolidar por RA
# - trazer Pedra 23 e Pedra 2023 lado a lado
# - classificar a situação entre as duas colunas
# ============================================================

df_tmp = df_fase5_p10[["RA", "Pedra 23", "Pedra 2023"]].copy()

# padroniza texto
for c in ["Pedra 23", "Pedra 2023"]:
    df_tmp[c] = df_tmp[c].astype("string").str.strip()

# função para pegar o primeiro valor não nulo
def primeiro_nao_nulo(serie):
    serie = serie.dropna()
    return serie.iloc[0] if len(serie) > 0 else pd.NA

# consolida por RA
df_validacao_2023 = (
    df_tmp
    .groupby("RA", as_index=False)
    .agg({
        "Pedra 23": primeiro_nao_nulo,
        "Pedra 2023": primeiro_nao_nulo
    })
)

# coluna de validação
def validar_pedra_2023(row):
    p23 = row["Pedra 23"]
    p2023 = row["Pedra 2023"]

    if pd.isna(p23) and pd.isna(p2023):
        return "AMBAS_VAZIAS"
    elif pd.notna(p23) and pd.notna(p2023) and p23 == p2023:
        return "IGUAL"
    elif pd.notna(p23) and pd.isna(p2023):
        return "COMPLEMENTAR_SO_PEDRA23"
    elif pd.isna(p23) and pd.notna(p2023):
        return "COMPLEMENTAR_SO_PEDRA2023"
    else:
        return "CONFLITO"

df_validacao_2023["validacao"] = df_validacao_2023.apply(validar_pedra_2023, axis=1)

print("Resumo da validação por RA:")
display(
    df_validacao_2023["validacao"]
    .value_counts(dropna=False)
    .rename_axis("validacao")
    .reset_index(name="quantidade")
)

print("\nAmostra da base consolidada por RA:")
display(df_validacao_2023.head(30))

Resumo da validação por RA:

                   validacao  quantidade
0               AMBAS_VAZIAS         730
1                      IGUAL         690
2  COMPLEMENTAR_SO_PEDRA2023         241

Amostra da base consolidada por RA:

         RA  Pedra 23 Pedra 2023                  validacao
0      RA-1      <NA>       <NA>               AMBAS_VAZIAS
1     RA-10      <NA>       <NA>               AMBAS_VAZIAS
2    RA-100      <NA>       <NA>               AMBAS_VAZIAS
3   RA-1000  Ametista   Ametista                      IGUAL
4   RA-1001   Topázio    Topázio                      IGUAL
5   RA-1002  Ametista   Ametista                      IGUAL
6   RA-1003  Ametista   Ametista                      IGUAL
7   RA-1004   Topázio    Topázio                      IGUAL
8   RA-1005      <NA>    Topázio  COMPLEMENTAR_SO_PEDRA2023
9   RA-1006   Topázio    Topázio                      IGUAL
10  RA-1007      <NA>    Topázio  COMPLEMENTAR_SO_PEDRA2023
11  RA-1008   Topázio    Topázio                      IGUAL
12  RA-1009  Ametista   Ametista                      IGUAL
13   RA-101      <NA>       <NA>               AMBAS_VAZIAS
14  RA-1010      <NA>    Topázio  COMPLEMENTAR_SO_PEDRA2023
15  RA-1011      <NA>   Ametista  COMPLEMENTAR_SO_PEDRA2023
16  RA-1012  Ametista   Ametista                      IGUAL
17  RA-1013  Ametista   Ametista                      IGUAL
18  RA-1014   Topázio    Topázio                      IGUAL
19  RA-1015  Ametista   Ametista                      IGUAL
20  RA-1016      <NA>   Ametista  COMPLEMENTAR_SO_PEDRA2023
21  RA-1017     Agata      Agata                      IGUAL
22  RA-1018     Agata      Agata                      IGUAL
23  RA-1019  Ametista   Ametista                      IGUAL
24   RA-102      <NA>       <NA>               AMBAS_VAZIAS
25  RA-1020  Ametista   Ametista                      IGUAL
26  RA-1021     Agata      Agata                      IGUAL
27  RA-1022  Ametista   Ametista                      IGUAL
28  RA-1023   Topázio    Topázio                      IGUAL
29  RA-1024  Ametista   Ametista                      IGUAL

In [22]:
# ============================================================
# BLOCO P10.18 — PREENCHER PEDRA 23 COM PEDRA 2023
# Objetivo:
# - completar a coluna Pedra 23
# - usar Pedra 2023 apenas quando Pedra 23 estiver nula
# ============================================================

df_fase5_p10 = df_fase5_p10.copy()

df_fase5_p10["Pedra 23"] = df_fase5_p10["Pedra 23"].fillna(df_fase5_p10["Pedra 2023"])

print("Nulos em Pedra 23 após preenchimento:")
print(df_fase5_p10["Pedra 23"].isna().sum())

print("\nAmostra das colunas após ajuste:")
display(df_fase5_p10[["RA", "Pedra 23", "Pedra 2023"]].head(20))

Nulos em Pedra 23 após preenchimento:
1409

Amostra das colunas após ajuste:

       RA Pedra 23 Pedra 2023
0    RA-1      NaN        NaN
1    RA-2      NaN        NaN
2    RA-3      NaN        NaN
3    RA-4      NaN        NaN
4    RA-5      NaN        NaN
5    RA-6      NaN        NaN
6    RA-7      NaN        NaN
7    RA-8      NaN        NaN
8    RA-9      NaN        NaN
9   RA-10      NaN        NaN
10  RA-11      NaN        NaN
11  RA-12      NaN        NaN
12  RA-13      NaN        NaN
13  RA-14      NaN        NaN
14  RA-15      NaN        NaN
15  RA-16      NaN        NaN
16  RA-17      NaN        NaN
17  RA-18      NaN        NaN
18  RA-19      NaN        NaN
19  RA-20      NaN        NaN

In [23]:
# ============================================================
# BLOCO P10.15 — VALIDAR PEDRA 23 x PEDRA 2023 POR RA
# Objetivo:
# - consolidar por RA
# - trazer Pedra 23 e Pedra 2023 lado a lado
# - classificar a situação entre as duas colunas
# ============================================================

df_tmp = df_fase5_p10[["RA", "Pedra 23", "Pedra 2023"]].copy()

# padroniza texto
for c in ["Pedra 23", "Pedra 2023"]:
    df_tmp[c] = df_tmp[c].astype("string").str.strip()

# função para pegar o primeiro valor não nulo
def primeiro_nao_nulo(serie):
    serie = serie.dropna()
    return serie.iloc[0] if len(serie) > 0 else pd.NA

# consolida por RA
df_validacao_2023 = (
    df_tmp
    .groupby("RA", as_index=False)
    .agg({
        "Pedra 23": primeiro_nao_nulo,
        "Pedra 2023": primeiro_nao_nulo
    })
)

# coluna de validação
def validar_pedra_2023(row):
    p23 = row["Pedra 23"]
    p2023 = row["Pedra 2023"]

    if pd.isna(p23) and pd.isna(p2023):
        return "AMBAS_VAZIAS"
    elif pd.notna(p23) and pd.notna(p2023) and p23 == p2023:
        return "IGUAL"
    elif pd.notna(p23) and pd.isna(p2023):
        return "COMPLEMENTAR_SO_PEDRA23"
    elif pd.isna(p23) and pd.notna(p2023):
        return "COMPLEMENTAR_SO_PEDRA2023"
    else:
        return "CONFLITO"

df_validacao_2023["validacao"] = df_validacao_2023.apply(validar_pedra_2023, axis=1)

print("Resumo da validação por RA:")
display(
    df_validacao_2023["validacao"]
    .value_counts(dropna=False)
    .rename_axis("validacao")
    .reset_index(name="quantidade")
)

Resumo da validação por RA:

      validacao  quantidade
0         IGUAL         931
1  AMBAS_VAZIAS         730

In [24]:
# ============================================================
# BLOCO — TRANSFORMAR AS PEDRAS EM BASE LONGA POR ALUNO
# Objetivo:
# - reorganizar as colunas de pedra em formato longitudinal
# - manter apenas registros com pedra preenchida
# ============================================================

df_base = df_fase5_p10.copy()

colunas_pedra = {
    "Pedra 21": 1,
    "Pedra 22": 2,
    "Pedra 23": 3,
    "Pedra 2024": 4,
    "PEDRA_final": 5
}

bases = []

for col, ordem in colunas_pedra.items():
    df_temp = df_base[["RA", col]].copy()
    df_temp = df_temp.rename(columns={col: "pedra"})
    df_temp["pedra_referencia"] = col
    df_temp["ordem_referencia"] = ordem
    bases.append(df_temp)

df_pedra_long = pd.concat(bases, ignore_index=True)

df_pedra_long = df_pedra_long[["RA", "pedra_referencia", "ordem_referencia", "pedra"]].copy()

# remove linhas sem pedra
df_pedra_long = df_pedra_long[df_pedra_long["pedra"].notna()].copy()

print("Dimensão da base longa:")
print(df_pedra_long.shape)

print("\nAmostra:")
display(df_pedra_long.head(20))

print("\nNulos por coluna:")
print(df_pedra_long.isna().sum())

Dimensão da base longa:
(8589, 4)

Amostra:

       RA pedra_referencia  ordem_referencia     pedra
0    RA-1         Pedra 21                 1  Ametista
1    RA-2         Pedra 21                 1  Ametista
2    RA-3         Pedra 21                 1  Ametista
3    RA-4         Pedra 21                 1  Ametista
4    RA-5         Pedra 21                 1  Ametista
5    RA-6         Pedra 21                 1     Ágata
6    RA-7         Pedra 21                 1  Ametista
7    RA-8         Pedra 21                 1     Ágata
8    RA-9         Pedra 21                 1  Ametista
9   RA-10         Pedra 21                 1     Ágata
10  RA-11         Pedra 21                 1     Ágata
11  RA-12         Pedra 21                 1     Ágata
12  RA-13         Pedra 21                 1  Ametista
21  RA-22         Pedra 21                 1     Ágata
22  RA-23         Pedra 21                 1  Ametista
23  RA-24         Pedra 21                 1   Topázio
24  RA-25         Pedra 21                 1   Topázio
26  RA-27         Pedra 21                 1  Ametista
27  RA-28         Pedra 21                 1  Ametista
29  RA-30         Pedra 21                 1  Ametista

Nulos por coluna:
RA                  0
pedra_referencia    0
ordem_referencia    0
pedra               0
dtype: int64

In [25]:
# ============================================================
# BLOCO — LISTAR AS PEDRAS EXISTENTES
# Objetivo:
# - mostrar quais valores existem na coluna de pedra
# - incluir a quantidade de ocorrências de cada uma
# ============================================================

print("Pedras existentes:")
display(df_pedra_long["pedra"].value_counts(dropna=False).rename_axis("pedra").reset_index(name="quantidade"))

Pedras existentes:

      pedra  quantidade
0  Ametista        3530
1   Topázio        2012
2     Agata        1095
3     Ágata        1013
4   Quartzo         863
5   INCLUIR          76

In [27]:
# ============================================================
# BLOCO — PADRONIZAR AS PEDRAS DA BASE LONGA E CRIAR SCORE
# Objetivo:
# - corrigir grafias diferentes da mesma pedra
# - remover valores inválidos como INCLUIR
# - criar score ordinal para análise de evolução
# ============================================================

df_pedra_long = df_pedra_long.copy()

df_pedra_long["pedra"] = df_pedra_long["pedra"].astype("string").str.strip()

df_pedra_long["pedra"] = df_pedra_long["pedra"].replace({
    "Agata": "Ágata",
    "AGATA": "Ágata",
    "Topazio": "Topázio",
    "TOPAZIO": "Topázio",
    "INCLUIR": pd.NA
})

df_pedra_long = df_pedra_long[df_pedra_long["pedra"].notna()].copy()

mapa_score_pedra = {
    "Quartzo": 1,
    "Ágata": 2,
    "Ametista": 3,
    "Topázio": 4
}

df_pedra_long["score_pedra"] = df_pedra_long["pedra"].map(mapa_score_pedra)

print("Pedras existentes após padronização:")
display(
    df_pedra_long["pedra"]
    .value_counts(dropna=False)
    .rename_axis("pedra")
    .reset_index(name="quantidade")
)

print("\nAmostra com score_pedra:")
display(df_pedra_long.head(20))

print("\nNulos em score_pedra:")
print(df_pedra_long["score_pedra"].isna().sum())

Pedras existentes após padronização:

      pedra  quantidade
0  Ametista        3530
1     Ágata        2108
2   Topázio        2012
3   Quartzo         863

Amostra com score_pedra:

       RA pedra_referencia  ordem_referencia     pedra  score_pedra
0    RA-1         Pedra 21                 1  Ametista            3
1    RA-2         Pedra 21                 1  Ametista            3
2    RA-3         Pedra 21                 1  Ametista            3
3    RA-4         Pedra 21                 1  Ametista            3
4    RA-5         Pedra 21                 1  Ametista            3
5    RA-6         Pedra 21                 1     Ágata            2
6    RA-7         Pedra 21                 1  Ametista            3
7    RA-8         Pedra 21                 1     Ágata            2
8    RA-9         Pedra 21                 1  Ametista            3
9   RA-10         Pedra 21                 1     Ágata            2
10  RA-11         Pedra 21                 1     Ágata            2
11  RA-12         Pedra 21                 1     Ágata            2
12  RA-13         Pedra 21                 1  Ametista            3
21  RA-22         Pedra 21                 1     Ágata            2
22  RA-23         Pedra 21                 1  Ametista            3
23  RA-24         Pedra 21                 1   Topázio            4
24  RA-25         Pedra 21                 1   Topázio            4
26  RA-27         Pedra 21                 1  Ametista            3
27  RA-28         Pedra 21                 1  Ametista            3
29  RA-30         Pedra 21                 1  Ametista            3

Nulos em score_pedra:
0

In [28]:
# ============================================================
# BLOCO — GERAR O SCORE FINAL DA PEDRA FINAL POR ALUNO
# Objetivo:
# - pegar a linha da PEDRA_final
# - gerar o score final de cada aluno
# ============================================================

df_score_final = (
    df_pedra_long[df_pedra_long["pedra_referencia"] == "PEDRA_final"]
    [["RA", "pedra", "score_pedra"]]
    .copy()
    .rename(columns={
        "pedra": "pedra_final",
        "score_pedra": "score_pedra_final"
    })
    .sort_values("RA")
    .reset_index(drop=True)
)

print("Dimensão da base de score final:")
print(df_score_final.shape)

print("\nAmostra:")
display(df_score_final.head(20))

print("\nDistribuição do score final:")
display(
    df_score_final["score_pedra_final"]
    .value_counts(dropna=False)
    .sort_index()
    .rename_axis("score_pedra_final")
    .reset_index(name="quantidade")
)

Dimensão da base de score final:
(2845, 3)

Amostra:

         RA pedra_final  score_pedra_final
0      RA-1     Quartzo                  1
1     RA-10     Quartzo                  1
2    RA-100    Ametista                  3
3   RA-1000     Topázio                  4
4   RA-1000    Ametista                  3
5   RA-1001    Ametista                  3
6   RA-1001     Topázio                  4
7   RA-1002    Ametista                  3
8   RA-1002    Ametista                  3
9   RA-1003    Ametista                  3
10  RA-1003    Ametista                  3
11  RA-1004    Ametista                  3
12  RA-1004     Topázio                  4
13  RA-1005     Topázio                  4
14  RA-1006    Ametista                  3
15  RA-1006     Topázio                  4
16  RA-1007     Topázio                  4
17  RA-1008       Ágata                  2
18  RA-1008     Topázio                  4
19  RA-1009       Ágata                  2

Distribuição do score final:

   score_pedra_final  quantidade
0                  1         316
1                  2         721
2                  3        1120
3                  4         688

In [29]:
# ============================================================
# BLOCO — GERAR SCORE INICIAL, FINAL E VARIAÇÃO POR ALUNO
# Objetivo:
# - identificar a primeira e a última pedra de cada aluno
# - calcular a variação final da trajetória
# ============================================================

df_traj = df_pedra_long.copy()

df_traj = df_traj.sort_values(["RA", "ordem_referencia"])

df_inicio_fim = (
    df_traj.groupby("RA")
    .agg(
        pedra_inicial=("pedra", "first"),
        score_inicial=("score_pedra", "first"),
        pedra_final=("pedra", "last"),
        score_final=("score_pedra", "last")
    )
    .reset_index()
)

df_inicio_fim["variacao_score"] = df_inicio_fim["score_final"] - df_inicio_fim["score_inicial"]

print("Amostra da trajetória inicial e final:")
display(df_inicio_fim.head(20))

print("\nDistribuição da variação do score:")
display(
    df_inicio_fim["variacao_score"]
    .value_counts(dropna=False)
    .sort_index()
    .rename_axis("variacao_score")
    .reset_index(name="quantidade")
)

Amostra da trajetória inicial e final:

,RA,pedra_inicial,score_inicial,pedra_final,score_final,variacao_score
0,RA-1,Ametista,3,Quartzo,1,-2
1,RA-10,Ágata,2,Quartzo,1,-1
2,RA-100,Topázio,4,Ametista,3,-1
3,RA-1000,Ametista,3,Topázio,4,1
4,RA-1001,Topázio,4,Ametista,3,-1
5,RA-1002,Ametista,3,Ametista,3,0
6,RA-1003,Ametista,3,Ametista,3,0
7,RA-1004,Topázio,4,Ametista,3,-1
8,RA-1005,Topázio,4,Topázio,4,0
9,RA-1006,Topázio,4,Ametista,3,-1
10,RA-1007,Topázio,4,Topázio,4,0
11,RA-1008,Topázio,4,Ágata,2,-2
12,RA-1009,Ametista,3,Ágata,2,-1
13,RA-101,Ametista,3,Ametista,3,0
14,RA-1010,Topázio,4,Topázio,4,0
15,RA-1011,Ametista,3,Ametista,3,0
16,RA-1012,Ametista,3,Topázio,4,1
17,RA-1013,Ametista,3,Quartzo,1,-2
18,RA-1014,Topázio,4,Ágata,2,-2
19,RA-1015,Ametista,3,Ágata,2,-1

Distribuição da variação do score:

   variacao_score  quantidade
0              -3           2
1              -2          56
2              -1         238
3               0        1066
4               1         205
5               2          18
6               3           1

In [35]:
# ============================================================
# BLOCO — TRANSFORMAR AS PEDRAS EM BASE LONGA (2022 A 2024)
# Objetivo:
# - reorganizar as colunas de pedra em formato longitudinal
# - considerar apenas o período oficial do Datathon: 2022 a 2024
# - manter apenas registros com pedra preenchida
# ============================================================

df_base = df_fase5_p10.copy()

colunas_pedra = {
    "Pedra 22": 1,
    "Pedra 23": 2,
    "Pedra 2024": 3
}

bases = []

for col, ordem in colunas_pedra.items():
    df_temp = df_base[["RA", col]].copy()
    df_temp = df_temp.rename(columns={col: "pedra"})
    df_temp["pedra_referencia"] = col
    df_temp["ordem_referencia"] = ordem
    bases.append(df_temp)

df_pedra_long = pd.concat(bases, ignore_index=True)

df_pedra_long = df_pedra_long[["RA", "pedra_referencia", "ordem_referencia", "pedra"]].copy()

# remove linhas sem pedra
df_pedra_long = df_pedra_long[df_pedra_long["pedra"].notna()].copy()

print("Dimensão da base longa:")
print(df_pedra_long.shape)

print("\nAmostra:")
display(df_pedra_long.head(20))

print("\nNulos por coluna:")
print(df_pedra_long.isna().sum())

Dimensão da base longa:
(4645, 4)

Amostra:

       RA pedra_referencia  ordem_referencia     pedra
0    RA-1         Pedra 22                 1   Quartzo
1    RA-2         Pedra 22                 1  Ametista
2    RA-3         Pedra 22                 1     Ágata
3    RA-4         Pedra 22                 1   Quartzo
4    RA-5         Pedra 22                 1  Ametista
5    RA-6         Pedra 22                 1   Quartzo
6    RA-7         Pedra 22                 1     Ágata
7    RA-8         Pedra 22                 1   Quartzo
8    RA-9         Pedra 22                 1   Topázio
9   RA-10         Pedra 22                 1   Quartzo
10  RA-11         Pedra 22                 1   Quartzo
11  RA-12         Pedra 22                 1   Quartzo
12  RA-13         Pedra 22                 1     Ágata
13  RA-14         Pedra 22                 1     Ágata
14  RA-15         Pedra 22                 1  Ametista
15  RA-16         Pedra 22                 1     Ágata
16  RA-17         Pedra 22                 1   Topázio
17  RA-18         Pedra 22                 1  Ametista
18  RA-19         Pedra 22                 1  Ametista
19  RA-20         Pedra 22                 1  Ametista

Nulos por coluna:
RA                  0
pedra_referencia    0
ordem_referencia    0
pedra               0
dtype: int64

In [36]:
# ============================================================
# BLOCO — BASE LONGA DE PEDRAS (2022 A 2024) COM PADRONIZAÇÃO E SCORE
# Objetivo:
# - considerar apenas 2022, 2023 e 2024
# - padronizar nomes das pedras
# - remover valores inválidos
# - criar score ordinal para análise de evolução
# ============================================================

df_base = df_fase5_p10.copy()

colunas_pedra = {
    "Pedra 22": 1,
    "Pedra 23": 2,
    "Pedra 2024": 3
}

bases = []

for col, ordem in colunas_pedra.items():
    df_temp = df_base[["RA", col]].copy()
    df_temp = df_temp.rename(columns={col: "pedra"})
    df_temp["pedra_referencia"] = col
    df_temp["ordem_referencia"] = ordem
    bases.append(df_temp)

df_pedra_long = pd.concat(bases, ignore_index=True)

df_pedra_long = df_pedra_long[["RA", "pedra_referencia", "ordem_referencia", "pedra"]].copy()

df_pedra_long["pedra"] = df_pedra_long["pedra"].astype("string").str.strip()

df_pedra_long["pedra"] = df_pedra_long["pedra"].replace({
    "Agata": "Ágata",
    "AGATA": "Ágata",
    "Topazio": "Topázio",
    "TOPAZIO": "Topázio",
    "INCLUIR": pd.NA
})

df_pedra_long = df_pedra_long[df_pedra_long["pedra"].notna()].copy()

mapa_score_pedra = {
    "Quartzo": 1,
    "Ágata": 2,
    "Ametista": 3,
    "Topázio": 4
}

df_pedra_long["score_pedra"] = df_pedra_long["pedra"].map(mapa_score_pedra)

print("Dimensão da base longa:")
print(df_pedra_long.shape)

print("\nAmostra:")
display(df_pedra_long.head(20))

print("\nDistribuição das pedras:")
display(
    df_pedra_long["pedra"]
    .value_counts(dropna=False)
    .rename_axis("pedra")
    .reset_index(name="quantidade")
)

print("\nNulos em score_pedra:")
print(df_pedra_long["score_pedra"].isna().sum())

Dimensão da base longa:
(4607, 5)

Amostra:

       RA pedra_referencia  ordem_referencia     pedra  score_pedra
0    RA-1         Pedra 22                 1   Quartzo            1
1    RA-2         Pedra 22                 1  Ametista            3
2    RA-3         Pedra 22                 1     Ágata            2
3    RA-4         Pedra 22                 1   Quartzo            1
4    RA-5         Pedra 22                 1  Ametista            3
5    RA-6         Pedra 22                 1   Quartzo            1
6    RA-7         Pedra 22                 1     Ágata            2
7    RA-8         Pedra 22                 1   Quartzo            1
8    RA-9         Pedra 22                 1   Topázio            4
9   RA-10         Pedra 22                 1   Quartzo            1
10  RA-11         Pedra 22                 1   Quartzo            1
11  RA-12         Pedra 22                 1   Quartzo            1
12  RA-13         Pedra 22                 1     Ágata            2
13  RA-14         Pedra 22                 1     Ágata            2
14  RA-15         Pedra 22                 1  Ametista            3
15  RA-16         Pedra 22                 1     Ágata            2
16  RA-17         Pedra 22                 1   Topázio            4
17  RA-18         Pedra 22                 1  Ametista            3
18  RA-19         Pedra 22                 1  Ametista            3
19  RA-20         Pedra 22                 1  Ametista            3

Distribuição das pedras:

      pedra  quantidade
0  Ametista        1910
1     Ágata        1156
2   Topázio        1099
3   Quartzo         442

Nulos em score_pedra:
0

In [38]:
# ============================================================
# BLOCO — CONSULTA DAS PEDRAS POR RA COM ANÁLISE DOS SCORES
# Objetivo:
# - montar uma visão por aluno com as pedras de 2022, 2023 e 2024
# - converter as pedras em scores ordinais
# - classificar a trajetória do aluno no período
# ============================================================

df_consulta_pedras = df_fase5_p10.copy()

colunas = ["RA", "Pedra 22", "Pedra 23", "Pedra 2024"]
df_consulta_pedras = df_consulta_pedras[colunas].copy()

# padroniza texto
for c in ["Pedra 22", "Pedra 23", "Pedra 2024"]:
    df_consulta_pedras[c] = df_consulta_pedras[c].astype("string").str.strip()

# padroniza grafias e remove valor inválido
mapa_padrao = {
    "Agata": "Ágata",
    "AGATA": "Ágata",
    "Topazio": "Topázio",
    "TOPAZIO": "Topázio",
    "INCLUIR": pd.NA
}

for c in ["Pedra 22", "Pedra 23", "Pedra 2024"]:
    df_consulta_pedras[c] = df_consulta_pedras[c].replace(mapa_padrao)

# função para pegar o primeiro valor não nulo por RA
def primeiro_nao_nulo(s):
    s = s.dropna()
    return s.iloc[0] if len(s) > 0 else pd.NA

# consolida por RA
df_consulta_pedras = (
    df_consulta_pedras
    .groupby("RA", as_index=False)
    .agg({
        "Pedra 22": primeiro_nao_nulo,
        "Pedra 23": primeiro_nao_nulo,
        "Pedra 2024": primeiro_nao_nulo
    })
)

# score ordinal das pedras
mapa_score = {
    "Quartzo": 1,
    "Ágata": 2,
    "Ametista": 3,
    "Topázio": 4
}

df_consulta_pedras["score_22"] = df_consulta_pedras["Pedra 22"].map(mapa_score)
df_consulta_pedras["score_23"] = df_consulta_pedras["Pedra 23"].map(mapa_score)
df_consulta_pedras["score_24"] = df_consulta_pedras["Pedra 2024"].map(mapa_score)

# análise da trajetória
def analisar_trajetoria(row):
    s22 = row["score_22"]
    s23 = row["score_23"]
    s24 = row["score_24"]

    scores = [x for x in [s22, s23, s24] if pd.notna(x)]

    if len(scores) < 2:
        return "Informação insuficiente"

    if scores == sorted(scores) and len(set(scores)) == 1:
        return "Estável"

    if scores == sorted(scores) and len(set(scores)) > 1:
        return "Melhora consistente"

    if scores == sorted(scores, reverse=True) and len(set(scores)) > 1:
        return "Piora consistente"

    if scores[-1] > scores[0]:
        return "Oscilou, mas melhorou no final"

    if scores[-1] < scores[0]:
        return "Oscilou, mas piorou no final"

    return "Oscilou e terminou estável"

df_consulta_pedras["analise"] = df_consulta_pedras.apply(analisar_trajetoria, axis=1)

print("Dimensão da base final:")
print(df_consulta_pedras.shape)

print("\nAmostra:")
display(df_consulta_pedras.head(20))

print("\nResumo da análise:")
display(
    df_consulta_pedras["analise"]
    .value_counts(dropna=False)
    .rename_axis("analise")
    .reset_index(name="quantidade")
)

Dimensão da base final:
(1661, 8)

Amostra:

,RA,Pedra 22,Pedra 23,Pedra 2024,score_22,score_23,score_24,analise
0,RA-1,Quartzo,<NA>,<NA>,1.0,NaN,NaN,Informação insuficiente
1,RA-10,Quartzo,<NA>,<NA>,1.0,NaN,NaN,Informação insuficiente
2,RA-100,Ametista,<NA>,<NA>,3.0,NaN,NaN,Informação insuficiente
3,RA-1000,<NA>,Ametista,Topázio,NaN,3.0,4.0,Melhora consistente
4,RA-1001,<NA>,Topázio,Ametista,NaN,4.0,3.0,Piora consistente
5,RA-1002,<NA>,Ametista,Ametista,NaN,3.0,3.0,Estável
6,RA-1003,<NA>,Ametista,Ametista,NaN,3.0,3.0,Estável
7,RA-1004,<NA>,Topázio,Ametista,NaN,4.0,3.0,Piora consistente
8,RA-1005,<NA>,Topázio,<NA>,NaN,4.0,NaN,Informação insuficiente
9,RA-1006,<NA>,Topázio,Ametista,NaN,4.0,3.0,Piora consistente
10,RA-1007,<NA>,Topázio,<NA>,NaN,4.0,NaN,Informação insuficiente
11,RA-1008,<NA>,Topázio,Ágata,NaN,4.0,2.0,Piora consistente
12,RA-1009,<NA>,Ametista,Ágata,NaN,3.0,2.0,Piora consistente
13,RA-101,Ametista,<NA>,<NA>,3.0,NaN,NaN,Informação insuficiente
14,RA-1010,<NA>,Topázio,<NA>,NaN,4.0,NaN,Informação insuficiente
15,RA-1011,<NA>,Ametista,<NA>,NaN,3.0,NaN,Informação insuficiente
16,RA-1012,<NA>,Ametista,Topázio,NaN,3.0,4.0,Melhora consistente
17,RA-1013,<NA>,Ametista,Quartzo,NaN,3.0,1.0,Piora consistente
18,RA-1014,<NA>,Topázio,Ágata,NaN,4.0,2.0,Piora consistente
19,RA-1015,<NA>,Ametista,Ágata,NaN,3.0,2.0,Piora consistente

Resumo da análise:

                          analise  quantidade
0         Informação insuficiente         836
1                         Estável         315
2               Piora consistente         210
3             Melhora consistente         205
4      Oscilou e terminou estável          77
5    Oscilou, mas piorou no final          10
6  Oscilou, mas melhorou no final           8

## Análise dos Scores das Pedras — Trajetória 2022 a 2024

Para avaliar a efetividade do programa no período oficial do Datathon, foi construída uma análise da trajetória dos alunos entre 2022, 2023 e 2024 a partir das colunas **Pedra 22**, **Pedra 23** e **Pedra 2024**.

As pedras foram convertidas em uma escala ordinal para permitir comparação objetiva entre os anos:

- **Quartzo = 1**
- **Ágata = 2**
- **Ametista = 3**
- **Topázio = 4**

Essa conversão permite interpretar a evolução do aluno da seguinte forma:

- aumento do score = avanço na trajetória
- manutenção do score = estabilidade
- redução do score = regressão

A análise foi feita por **RA**, consolidando as informações das três colunas de pedra e classificando a trajetória do aluno em categorias interpretáveis, como:

- **Melhora consistente**
- **Estável**
- **Piora consistente**
- **Oscilou, mas melhorou no final**
- **Oscilou, mas piorou no final**
- **Oscilou e terminou estável**
- **Informação insuficiente**

Essa abordagem é mais adequada para responder à Pergunta 10 porque não observa apenas a pedra final do aluno, mas sim sua trajetória ao longo do ciclo de 2022 a 2024.

Dessa forma, a análise permite verificar com mais robustez se houve melhora consistente nas diferentes fases do programa, oferecendo evidência mais concreta sobre o impacto real da intervenção educacional.